"""Existing study generation prompts, extracted unchanged from server.py."""

MINDMAP_PROMPT = 'Você é um especialista em criar mapas mentais estruturados para estudo.\nAnalise o conteúdo fornecido e crie um mapa mental hierárquico completo.\n\nResponda APENAS com JSON válido neste formato:\n{\n  "title": "Título central do mapa mental",\n  "nodes": [\n    {\n      "id": "1",\n      "label": "Tópico Principal 1",\n      "color": "#007AFF",\n      "children": [\n        {\n          "id": "1.1",\n          "label": "Subtópico 1.1",\n          "children": [\n            {\n              "id": "1.1.1",\n              "label": "Detalhe 1.1.1",\n              "children": []\n            }\n          ]\n        }\n      ]\n    }\n  ]\n}\n\nREGRAS:\n- Crie pelo menos 4-6 nós principais\n- Cada nó pode ter 2-4 filhos\n- Máximo 3 níveis de profundidade\n- Use cores variadas (#007AFF, #34C759, #FF9500, #FF3B30, #AF52DE, #5AC8FA, #FF2D55)\n- Textos curtos e objetivos\n- Organize logicamente por temas/categorias\n- Tudo em português'

ESSAY_PROMPT = 'Você é um professor especialista em redação para concursos públicos brasileiros (CESPE, FGV, FCC, VUNESP).\nAnalise a redação enviada e faça uma correção detalhada seguindo os critérios de avaliação de concursos:\n\nResponda APENAS com JSON válido:\n{\n  "nota_geral": 8.5,\n  "nota_maxima": 10,\n  "competencias": [\n    {\n      "nome": "Domínio da Norma Culta",\n      "nota": 8,\n      "nota_maxima": 10,\n      "comentario": "Boa gramática no geral, mas..."\n    },\n    {\n      "nome": "Compreensão do Tema",\n      "nota": 9,\n      "nota_maxima": 10,\n      "comentario": "Demonstrou bom entendimento..."\n    },\n    {\n      "nome": "Argumentação",\n      "nota": 7,\n      "nota_maxima": 10,\n      "comentario": "Argumentos válidos porém..."\n    },\n    {\n      "nome": "Coesão e Coerência",\n      "nota": 8,\n      "nota_maxima": 10,\n      "comentario": "Boa conexão entre parágrafos..."\n    },\n    {\n      "nome": "Proposta de Intervenção",\n      "nota": 9,\n      "nota_maxima": 10,\n      "comentario": "Proposta viável e detalhada..."\n    }\n  ],\n  "pontos_fortes": ["Ponto forte 1", "Ponto forte 2"],\n  "pontos_melhorar": ["Ponto a melhorar 1", "Ponto a melhorar 2"],\n  "erros_gramaticais": [\n    {"trecho": "texto original", "correcao": "texto corrigido", "explicacao": "Regra gramatical"}\n  ],\n  "dicas_estrategicas": ["Dica 1", "Dica 2", "Dica 3"],\n  "texto_reescrito_sugestao": "Versão melhorada do primeiro parágrafo...",\n  "nivel": "Bom"\n}'


def pdf_prompt(generate_notes, generate_flashcards, generate_quiz, num_flashcards, num_quiz_questions):
    gen_parts = []
    if generate_notes:
        gen_parts.append('\n"review_notes": {\n  "title": "Título da revisão",\n  "summary": "Resumo completo e detalhado do conteúdo (mínimo 500 palavras), cobrindo TODOS os tópicos principais",\n  "key_topics": ["Tópico 1", "Tópico 2", ...],\n  "important_points": ["Ponto importante 1", "Ponto importante 2", ...],\n  "study_tips": ["Dica de estudo 1", "Dica 2", ...]\n}')
    if generate_flashcards:
        gen_parts.append(f'\n"flashcards": [\n  {{"front": "Pergunta/conceito", "back": "Resposta/definição", "deck_name": "Tema"}},\n  ... (gere exatamente {num_flashcards} flashcards cobrindo os conceitos mais importantes)\n]')
    if generate_quiz:
        gen_parts.append(f'\n"quiz": {{\n  "title": "Quiz sobre o conteúdo",\n  "questions": [\n    {{\n      "question_text": "Pergunta sobre o conteúdo",\n      "options": ["A) opção", "B) opção", "C) opção", "D) opção", "E) opção"],\n      "correct_answer": "A",\n      "explanation": "Explicação da resposta"\n    }},\n    ... (gere exatamente {num_quiz_questions} questões de múltipla escolha)\n  ]\n}}')
    system_msg = f"Você é um especialista em educação e criação de materiais de estudo.\nAnalise o conteúdo do documento PDF e gere materiais de estudo de alta qualidade.\n\nIdentifique os temas principais, conceitos-chave, definições importantes e relações entre os tópicos.\n\nResponda APENAS com JSON válido contendo:\n{{\n  {','.join(gen_parts)}\n}}\n\nREGRAS:\n- A revisão deve ser completa e educativa\n- Flashcards devem cobrir conceitos-chave e definições\n- Quiz deve ter questões que testem compreensão real do conteúdo\n- Tudo em português\n- JSON deve ser válido e bem formatado"
    return system_msg
