import { useCallback, useEffect, useRef, useState } from 'react';
import axios from 'axios';
import EdictRadar from './EdictRadar';
import { Button } from '@/components/ui/button';
import { getApiErrorMessage } from '@/lib/api-errors';
const API = `${process.env.REACT_APP_BACKEND_URL || 'http://localhost:8000'}/api/study/v2/programs`;
const kinds = { OFFICIAL: 'Fonte oficial', SECONDARY: 'Fonte secundária', USER_PROVIDED: 'Fonte informada pelo usuário' };
export default function ContestUpdates({ programId, examsOnly = false }) {
  const [sources, setSources] = useState([]), [updates, setUpdates] = useState([]), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ title: '', url: '', terms_allow_monitoring: false, source_kind: 'unknown' });
  const [refresh, setRefresh] = useState(0);
  const active = useRef(0), mutating = useRef(false);
  const load = useCallback(async () => { const current = active.current; const [s, u] = await Promise.all([axios.get(`${API}/${programId}/sources`), axios.get(`${API}/${programId}/${examsOnly ? 'exams' : 'timeline'}`)]); if (current === active.current) { setSources(s.data); setUpdates(u.data); } }, [programId, examsOnly]);
  useEffect(() => { active.current += 1; mutating.current = false; setBusy(false); setSources([]); setUpdates([]); setError(''); setNotice(''); setForm({ title: '', url: '', terms_allow_monitoring: false, source_kind: 'unknown' }); const current = active.current; load().catch(() => { if (current === active.current) setError('Não foi possível carregar as fontes.'); }); return () => { active.current += 1; }; }, [load]);
  const run = async operation => { if (mutating.current) return; mutating.current = true; const current = active.current; setBusy(true); setError(''); setNotice(''); try { await operation(current); if (current === active.current) { await load(); setRefresh(n => n + 1); } } catch (e) { if (current === active.current) setError(getApiErrorMessage(e)); } finally { if (current === active.current) { mutating.current = false; setBusy(false); } } };
  return <section className="space-y-6 min-w-0 [overflow-wrap:anywhere]"><div><h2 className="text-xl font-semibold">{examsOnly ? 'Provas e gabaritos' : 'Acompanhar atualizações'}</h2><p className="text-sm text-slate-400 mt-2">{examsOnly ? 'Links encontrados nas fontes acompanhadas. Confira o cargo, a edição e o documento original.' : 'Acompanhe páginas públicas com consultas espaçadas. Uma alteração detectada não significa uma retificação oficial.'}</p></div>
    {error && <p role="alert" className="text-amber-300">{error}</p>}{notice && <p role="status" className="text-green-300">{notice}</p>}
    {!examsOnly && <><details><summary className="cursor-pointer text-sm text-purple-300">Adicionar página ou PDF para acompanhamento</summary><form className="space-y-3 mt-4" onSubmit={e => { e.preventDefault(); run(async current => { await axios.post(`${API}/${programId}/sources`, form); if (current !== active.current) return; setForm({ title: '', url: '', terms_allow_monitoring: false, source_kind: 'unknown' }); setNotice('Fonte adicionada. A primeira consulta ocorrerá automaticamente.'); }); }}><label className="block text-sm">Nome da fonte<input required maxLength={180} value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className="block w-full bg-slate-900 rounded-lg p-2 mt-1" /></label><label className="block text-sm">Página ou PDF público HTTPS<input type="url" required value={form.url} onChange={e => setForm({ ...form, url: e.target.value })} className="block w-full bg-slate-900 rounded-lg p-2 mt-1" placeholder="https://…" /></label><label className="block text-sm">Tipo declarado da fonte<select value={form.source_kind} onChange={e => setForm({ ...form, source_kind: e.target.value })} className="block w-full bg-slate-900 rounded-lg p-2 mt-1">{Object.entries({ unknown: "Outro / desconhecido", official_page: "Página oficial", board: "Banca", official_pdf: "PDF oficial", rectification: "Retificação", announcement: "Comunicado", result: "Resultado", calendar: "Calendário" }).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><span className="text-xs text-slate-400">A declaração não altera a verificação do domínio.</span></label><label className="flex gap-2 text-xs text-slate-400"><input type="checkbox" required checked={form.terms_allow_monitoring} onChange={e => setForm({ ...form, terms_allow_monitoring: e.target.checked })} />Conferi que os termos da página permitem consultas automáticas. O Sirius também respeita robots e bloqueios de acesso.</label><Button disabled={busy} type="submit">Acompanhar fonte</Button></form></details>
    <div>{sources.map(s => <article className="py-4 border-b border-slate-800" key={s.source_id}><div className="flex flex-wrap justify-between gap-3"><div><a href={s.url} target="_blank" rel="noopener noreferrer" className="text-sky-300">{s.title} ↗</a><p className="text-xs text-slate-400 mt-1">{kinds[s.trust]} · {s.last_checked ? `Verificada em ${new Date(s.last_checked).toLocaleString('pt-BR')}` : 'Aguardando primeira consulta'}</p>{s.error && <p className="text-xs text-amber-300 mt-2">{s.error}</p>}</div><div className="flex flex-wrap gap-2"><Button variant="ghost" disabled={busy} onClick={() => run(async current => { const r = await axios.post(`${API}/${programId}/sources/${s.source_id}/poll`); if (current !== active.current) return; setNotice(r.data.message); })}>Verificar</Button><Button variant="ghost" disabled={busy} onClick={() => run(() => axios.delete(`${API}/${programId}/sources/${s.source_id}`))}>Parar acompanhamento</Button></div></div></article>)}</div></>}
    {!examsOnly && <EdictRadar programId={programId} refresh={refresh} />}
    <ol className="space-y-5">{updates.map(u => <li key={u.update_id} className="border-l-2 border-purple-400/30 pl-4"><p className="text-xs text-slate-500">Detectado em {new Date(u.detected_at).toLocaleString('pt-BR')} · {kinds[u.source_type]}</p><a href={u.url} target="_blank" rel="noopener noreferrer" className="block text-sky-200 font-medium mt-1">{u.title} ↗</a><p className="text-xs text-slate-400 mt-1">{u.source} · data de publicação {u.published_at || 'não confirmada'}</p>{u.changes && <details className="mt-3 text-sm"><summary className="cursor-pointer">Comparar texto das versões</summary><p className="text-xs text-slate-400 my-2">Mudanças textuais, sem interpretação jurídica. Confira datas, cargos e conteúdo no documento original.{u.changes.partial && ' Comparação parcial por limite de exibição.'}</p><div className="grid sm:grid-cols-2 gap-3"><div><h4 className="text-green-300">Adicionado</h4>{u.changes.added.map((line, i) => <p key={i} className="text-xs break-words my-2">+ {line}</p>)}</div><div><h4 className="text-rose-300">Removido</h4>{u.changes.removed.map((line, i) => <p key={i} className="text-xs break-words my-2">− {line}</p>)}</div></div></details>}</li>)}</ol>
    {updates.length === 0 && <p className="text-sm text-slate-400">Nenhum {examsOnly ? 'caderno de prova ou gabarito encontrado' : 'documento detectado'} nas fontes acompanhadas ainda.</p>}
  </section>;
}
