import { useEffect, useRef, useState } from 'react';
import axios from 'axios';
import { Button } from '@/components/ui/button';
import { getApiErrorMessage } from '@/lib/api-errors';
const API = `${process.env.REACT_APP_BACKEND_URL || 'http://localhost:8000'}/api/study/v2/programs`;
export default function ExamBlueprint({ programId, onStart }) {
  const [plan, setPlan] = useState(null), [minutes, setMinutes] = useState(120), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [mode, setMode] = useState('edital'), [count, setCount] = useState(20), [selected, setSelected] = useState([]), [confirmed, setConfirmed] = useState(false);
  const [rules, setRules] = useState({ wrong_penalty: 0, blank_penalty: 0, scoring_source: '', scoring_excerpt: '', confirm_scoring_source: false });
  const pending = useRef(null), lock = useRef(false), generation = useRef(0);
  useEffect(() => { const c = new AbortController(); const scope = ++generation.current; lock.current = false; setBusy(false); setError(''); setPlan(null); setSelected([]); pending.current = null;
    axios.get(`${API}/${programId}/blueprint`, { signal: c.signal }).then(r => { if (!c.signal.aborted) setPlan(r.data); }).catch(() => { if (!c.signal.aborted) setError('Não foi possível carregar a distribuição.'); }); return () => { c.abort(); generation.current = scope + 1; }; }, [programId]);
  const create = async () => {
    if (lock.current) return; lock.current = true; setBusy(true); setError('');
    const scope = generation.current;
    const body = { title: 'Simulado · ' + mode, duration_minutes: minutes, mode, num_questions: count,
      notebook_ids: mode === 'discipline' ? selected : [], topic_ids: mode === 'topics' ? selected : [], confirm_provisional: confirmed, ...rules };
    const fingerprint = JSON.stringify([programId, body]);
    if (pending.current?.fingerprint !== fingerprint) pending.current = { fingerprint, key: crypto.randomUUID() };
    try { const { data } = await axios.post(`${API}/${programId}/blueprint/simulado`, body, { headers: { 'Idempotency-Key': pending.current.key } }); if (scope === generation.current) { pending.current = null; onStart(data); } }
    catch (e) { if (scope === generation.current) setError(getApiErrorMessage(e, 'Não foi possível montar o simulado.')); }
    finally { if (scope === generation.current) { setBusy(false); lock.current = false; } }
  };
  const choices = mode === 'discipline' ? plan?.disciplines : plan?.topics;
  return <section aria-label="Exam Blueprint" className="py-5 border-b border-slate-700 space-y-4 min-w-0 [&_button]:min-h-11"><h3 className="text-lg font-medium">Monte sua próxima prova</h3><p className="text-sm text-slate-400">Reutiliza questões canônicas com gabarito. Questões sintéticas mantêm a identificação de IA. Pontos fracos usam o Strategy Engine existente.</p>
    <label className="block text-sm">Modo<select aria-label="Modo do simulado" value={mode} disabled={busy} onChange={e => { setMode(e.target.value); setSelected([]); }} className="block w-full rounded-xl bg-slate-900 p-3"><option value="edital">Estrutura registrada do edital</option><option value="discipline">Por disciplinas</option><option value="topics">Por assuntos</option><option value="weak">Pontos fracos</option><option value="quick">Revisão rápida (até 10)</option></select></label>
    {mode === 'edital' ? <><div className="space-y-2">{plan?.distribution?.map(row => <div className="flex flex-wrap justify-between gap-2 text-sm" key={row.notebook_id}><span>{row.name}</span><span>{row.count} questões · peso {row.weight} · {row.provenance === 'source_recorded' ? 'fonte registrada' : 'provisório'}</span></div>)}</div><p className="text-xs text-amber-200">{plan?.notice}</p><label className="flex gap-3 items-start text-sm"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e => setConfirmed(e.target.checked)} className="mt-1" />Conferi os registros ou aceito os dados provisórios apenas para prática. Não são regras oficiais confirmadas.</label></> : <label className="block text-sm">Quantidade<input aria-label="Quantidade de questões" type="number" min="1" max="200" value={count} disabled={busy} onChange={e => setCount(Number(e.target.value))} className="block bg-slate-900 rounded-lg p-3" /></label>}
    {(mode === 'discipline' || mode === 'topics') && <div className="max-h-64 overflow-y-auto border border-slate-700 rounded-xl p-3">{choices?.map(row => <label key={row.id} className="flex gap-3 py-3 text-sm"><input type="checkbox" checked={selected.includes(row.id)} disabled={busy || (selected.length >= 100 && !selected.includes(row.id))} onChange={e => setSelected(old => e.target.checked ? [...old, row.id] : old.filter(id => id !== row.id))} />{row.name}</label>)}</div>}
    <details className="rounded-xl border border-slate-700 p-3"><summary className="cursor-pointer py-2">Regras de pontuação com fonte</summary><p className="text-xs text-slate-400 py-2">Padrão: um peso por acerto, zero por erro ou branco. Só configure penalização após conferir a fonte. O Sirius não valida sua declaração como oficial.</p>{[['wrong_penalty', 'Desconto por erro · múltiplo do peso'], ['blank_penalty', 'Desconto por branco · múltiplo do peso']].map(([key, label]) => <label className="block text-sm py-2" key={key}>{label}<input type="number" min="0" max="100" step="0.1" value={rules[key]} disabled={busy} onChange={e => setRules(old => ({ ...old, [key]: Number(e.target.value) }))} className="block w-full bg-slate-900 p-3 rounded-lg" /></label>)}<label className="block text-sm py-2">Fonte da regra<input value={rules.scoring_source} maxLength={500} disabled={busy} onChange={e => setRules(old => ({ ...old, scoring_source: e.target.value }))} className="block w-full bg-slate-900 p-3 rounded-lg" /></label><label className="block text-sm py-2">Trecho e página<textarea value={rules.scoring_excerpt} maxLength={2000} disabled={busy} onChange={e => setRules(old => ({ ...old, scoring_excerpt: e.target.value }))} className="block w-full bg-slate-900 p-3 rounded-lg" /></label><label className="flex gap-3 text-sm py-3"><input type="checkbox" checked={rules.confirm_scoring_source} disabled={busy} onChange={e => setRules(old => ({ ...old, confirm_scoring_source: e.target.checked }))} />Conferi a regra na fonte informada.</label></details>
    <label className="block text-sm">Duração em minutos · definida por você<input aria-label="Duração do simulado" type="number" min="1" max="600" value={minutes} disabled={busy} onChange={e => setMinutes(Number(e.target.value))} className="block bg-slate-900 rounded-lg p-3" /></label>{error && <p role="alert" className="text-amber-300 text-sm">{error}</p>}<Button disabled={busy || !plan || (mode === 'edital' && !plan.complete) || minutes < 1 || minutes > 600 || count < 1 || count > 200 || (['topics', 'discipline'].includes(mode) && !selected.length)} onClick={create}>{busy ? 'Montando…' : 'Montar simulado'}</Button>
  </section>;
}
