import { useState } from 'react';
import { Button } from '@/components/ui/button';
export default function ExamPostMortem({ result, attempts = [], onAttempt, onReviewErrors }) {
  const [show, setShow] = useState(false);
  const p = result.post_mortem;
  return <section aria-label="Diagnóstico do simulado" className="rounded-2xl border border-slate-700 p-5 space-y-4 min-w-0">
    <h3 className="font-semibold">Depois da prova</h3>
    {result.raw_points != null && <div className="text-sm space-y-2"><p>Pontos líquidos: {result.raw_points} / {result.maximum_points}. Percentual exibido: {result.score}% (piso zero).</p><p>Penalização por erro: {result.scoring_rules?.wrong_penalty || 0} × peso; branco: {result.scoring_rules?.blank_penalty || 0} × peso.</p>{result.scoring_rules?.source && <p className="break-words">Fonte declarada: {result.scoring_rules.source} · {result.scoring_rules.excerpt}. Confirmada pelo usuário; sem verificação oficial automática.</p>}</div>}
    {p ? <><p className="text-sm text-slate-400">{p.notice}</p><div className="grid sm:grid-cols-2 gap-3">{Object.entries(p.by_discipline).map(([name, d]) => <div key={name} className="rounded-xl bg-slate-900 p-3 text-sm break-words"><p className="font-medium">{name}</p><p>{d.wrong} erros · {d.blank} em branco · {d.points_lost} pontos de peso perdidos</p><p>{d.mean_seconds == null ? 'Tempo por questão não informado' : `${d.mean_seconds}s em média · ${d.timed_questions} questões cronometradas`}</p></div>)}</div><p className="text-sm">{p.slow_question_indexes.length} questões acima do orçamento médio · {p.changed_answers} respostas alteradas · {p.repeated_wrong_question_ids.length} erros repetidos na mesma questão.</p>{p.time_overrun && <p className="text-amber-300 text-sm">Tempo de interação acima da duração definida para a prática.</p>}<details className="text-sm"><summary className="cursor-pointer min-h-11 py-3">Tempo por assunto e tipo</summary>{Object.entries(p.speed_profile || {}).map(([kind, groups]) => <div key={kind}>{Object.entries(groups).map(([name, d]) => <p key={name} className="break-words">{name}: {d.mean_seconds}s em média · {d.samples} observações</p>)}</div>)}</details><h4 className="text-sm font-medium">Confiança e resultado</h4>{Object.entries(p.confidence).map(([name, d]) => <p className="text-sm" key={name}>{({ guess: 'Chute', uncertain: 'Incerto', confident: 'Confiante' })[name]}: {d.correct}/{d.answered} acertos ({d.accuracy}%). Chutes corretos continuam visíveis como evidência de confiança limitada nas revisões existentes.</p>)}{!Object.keys(p.confidence).length && <p className="text-sm text-slate-400">Sem confiança declarada; não é possível avaliar sua calibração.</p>}</> : <p className="text-sm text-slate-400">Tentativa histórica sem os novos metadados de diagnóstico.</p>}
    <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setShow(!show)}>{show ? 'Ocultar evolução' : 'Ver evolução entre tentativas'}</Button><Button variant="outline" onClick={onReviewErrors}>Revisar erros no banco</Button></div>
    {show && <ol className="space-y-2">{attempts.map(a => <li key={a.attempt_id}><button className="w-full text-left rounded-lg bg-slate-900 p-3 min-h-11 text-sm" onClick={() => onAttempt(a)}>{new Date(a.completed_at).toLocaleString('pt-BR')} · {a.score}% · {a.correct_count}/{a.total_questions} acertos</button></li>)}</ol>}
  </section>;
}
