import { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { Button } from '@/components/ui/button';
import IndividualPractice from './IndividualPractice';
import QuestionIntelligence from './QuestionIntelligence';
import { questionOriginLabel } from '@/lib/question-origin';
import { errorLabels } from '@/lib/study-errors';
const API = `${process.env.REACT_APP_BACKEND_URL || 'http://localhost:8000'}/api/study/v2`;
export default function MasteryDashboard({ programId, onStudy }) {
  const [data, setData] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(null);
  const load = useCallback(() => axios.get(`${API}/performance`, { params: { program_id: programId } }).then(r => setData(r.data)), [programId]);
  useEffect(() => { load().catch(() => setError('Não foi possível carregar o desempenho.')); }, [load]);
  const classify = async (id, reason) => { setBusy(id); setError(''); try { await axios.patch(`${API}/attempts/${id}/error`, { reason }); await load(); } catch { setError('Não foi possível salvar a classificação.'); } finally { setBusy(null); } };
  return <section className="space-y-7"><div><h2 className="text-xl font-semibold">Domínio e banco de erros</h2><p className="text-sm text-slate-400 mt-2">Cobertura indica o que você estudou. Domínio é uma estimativa calculada a partir das respostas individuais, com maior peso para as recentes.</p></div>
    {error && <p role="alert" className="text-amber-300">{error}</p>}
    <div className="flex flex-wrap gap-8"><div><p className="text-sm text-slate-400">Domínio estimado</p><strong className="text-3xl">{data?.summary?.score == null ? 'Sem amostra' : `${data.summary.score}%`}</strong></div><div><p className="text-sm text-slate-400">Base da estimativa</p><strong className="text-xl">{data?.summary?.samples ?? 0} questões</strong></div></div>
    {data?.truncated && <p className="text-amber-300 text-sm">Exibindo as últimas {data.sample_limit} respostas.</p>}
    {!!data?.trend?.length && <details className="rounded-xl border border-slate-800 p-4"><summary className="cursor-pointer">Evolução dos acertos · últimos 30 dias com respostas</summary><ul className="mt-4 space-y-3">{data.trend.map(day => <li key={day.date} className="text-xs"><div className="flex justify-between gap-3 mb-1"><span>{day.date}</span><span>{day.correct}/{day.total} · {day.accuracy}%</span></div><progress className="w-full h-2 accent-purple-400" max="100" value={day.accuracy} aria-label={`Acertos em ${day.date}`} /></li>)}</ul></details>}
    {!!data?.errors?.length && <details className="rounded-xl border border-slate-800 p-4"><summary className="cursor-pointer">Refazer questões do banco de erros</summary>{data.errors.slice(0, 20).map(a => <div key={a.attempt_id} className="mt-4"><p className="text-sm">{a.title}</p><IndividualPractice previous={a} notebookId={a.notebook_id} topicKey={a.topic_key} onSaved={load} /></div>)}</details>}
    <div>{(data?.topics || []).map(t => <div key={`${t.notebook_id}:${t.topic_key}`} className="flex flex-wrap justify-between items-center gap-4 py-4 border-b border-slate-800"><div><p>{t.title}</p><p className="text-xs text-slate-400 mt-1">{t.samples} respostas · confiança {({ low: 'baixa', medium: 'moderada', high: 'alta' })[t.confidence]} · intervalo estimado {t.range?.join('–')}%</p></div><div className="flex items-center gap-4"><strong>{t.score}%</strong><Button variant="ghost" onClick={() => onStudy(t)}>Estudar</Button></div></div>)}</div>
    {data && <QuestionIntelligence programId={programId} refresh={data} onStudy={onStudy} />}
    <section><h3 className="font-medium mb-3">Por que estou errando?</h3><div className="flex flex-wrap gap-3 text-sm">{Object.entries(data?.error_causes || {}).map(([reason, count]) => <span key={reason} className="bg-slate-800 rounded-lg px-3 py-2">{errorLabels[reason] || 'Sem classificação'}: {count}</span>)}</div></section>
    <section><h3 className="font-medium mb-3">Erros recentes · refazer e revisar</h3>{!(data?.errors || []).length && <p className="text-slate-400 text-sm">Nenhum erro individual registrado.</p>}{(data?.errors || []).map(a => <article key={a.attempt_id} className="py-4 border-b border-slate-800 space-y-2"><p className="text-xs text-purple-300">{a.title} · {a.date}</p><p className="text-sm whitespace-pre-wrap">{a.question}</p><p className="text-xs text-slate-400">{questionOriginLabel(a.question_provenance)}</p><div className="flex flex-wrap gap-3"><select aria-label={`Motivo do erro: ${a.title}`} value={a.error_reason || ''} disabled={busy === a.attempt_id} onChange={e => classify(a.attempt_id, e.target.value)} className="bg-slate-900 border border-slate-700 p-2 rounded-lg text-sm"><option value="" disabled>Classificar erro</option>{Object.entries(errorLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><Button variant="ghost" onClick={() => onStudy(a)}>Revisar assunto</Button></div></article>)}</section>
  </section>;
}
