import { useEffect, useState } from 'react';
import axios from 'axios';
import { Button } from '@/components/ui/button';
const API = `${process.env.REACT_APP_BACKEND_URL || 'http://localhost:8000'}/api/study/v2/programs`;
const stages = { not_started: 'Não iniciado', exposed: 'Contato inicial', practicing: 'Em prática', consolidating: 'Consolidando', mastered: 'Domínio sustentado', maintenance: 'Manutenção' };
const health = { insufficient: 'Evidência insuficiente', attention: 'Precisa de atenção', moderate: 'Em consolidação', stable: 'Indicadores estáveis' };
const kinds = { question: 'Questão', session: 'Sessão', review: 'Revisão', flashcard: 'Flashcard', practice: 'Prática agregada', exam: 'Simulado', essay: 'Redação' };

export default function PreparationState({ programId, onStudy }) {
  const [data, setData] = useState(null), [error, setError] = useState(''), [reload, setReload] = useState(0);
  const [visibleTopics, setVisibleTopics] = useState(20);
  useEffect(() => {
    const controller = new AbortController(); setData(null); setError(''); setVisibleTopics(20);
    axios.get(`${API}/${programId}/state`, { signal: controller.signal }).then(r => {
      if (!Array.isArray(r.data?.health?.components) || !Array.isArray(r.data?.syllabus_graph?.topics)) throw new Error('Invalid preparation state');
      if (!controller.signal.aborted) setData(r.data);
    }).catch(() => { if (!controller.signal.aborted) setError('Não foi possível carregar o estado da preparação.'); });
    return () => controller.abort();
  }, [programId, reload]);
  if (error) return <div role="alert" className="py-4 space-y-2"><p>{error}</p><Button variant="outline" onClick={() => setReload(v => v + 1)}>Tentar novamente</Button></div>;
  if (!data) return <p role="status" className="text-sm text-slate-400 py-4">Calculando indicadores a partir dos seus registros…</p>;
  return <section aria-label="Estado da preparação" className="space-y-5 py-4 min-w-0">
    <div><h2 className="font-semibold">Sua preparação · {health[data.health.status]}</h2><p className="text-xs text-slate-400 mt-1">{data.health.notice}</p></div>
    {data.target && <p className="text-sm text-slate-400">{[data.target.institution, data.target.board, data.target.edition, data.target.position].filter(Boolean).join(' · ')}{data.days_remaining != null ? ` · ${data.days_remaining >= 0 ? `${data.days_remaining} dias até a prova/meta` : 'Data da prova/meta já passou'}` : ' · Data da prova/meta não definida'}</p>}
    {data.truncated && <p role="status" className="text-amber-300 text-sm">Amostra limitada. Os indicadores não representam todo o histórico.</p>}
    <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-x-5 gap-y-3">{data.health.components.map(c => <details key={c.key} className="rounded-lg border border-slate-700 p-3 min-w-0"><summary className="cursor-pointer min-h-[44px] flex items-center justify-between gap-2"><span className="text-sm">{c.title}</span><strong>{c.value == null ? 'Sem dados' : `${c.value}%`}</strong></summary><p className="text-xs text-slate-400 mt-2 break-words">{c.reason}</p></details>)}</div>
    <p className="text-sm text-slate-300">Últimos 7 dias: <strong>{data.current_pace.minutes_per_week} min</strong> estudados. {data.study_debt.overdue_blocks} blocos pendentes nos últimos 28 dias ({data.study_debt.minutes} min). Revisões de assuntos vencidas: {data.reviews_due.topics}; flashcards: {data.reviews_due.flashcards}.</p>
    <details><summary className="cursor-pointer py-3 min-h-[44px] text-sm">Por que este ritmo?</summary><p className="text-sm text-slate-400">{data.required_pace.notice}</p><p className="text-sm mt-2">Carga registrada no plano dos últimos 7 dias: {data.required_pace.minutes_per_week == null ? 'sem plano' : `${data.required_pace.minutes_per_week} min`}. Média de sessão: {data.candidate_model.mean_duration_minutes == null ? 'sem sessões' : `${data.candidate_model.mean_duration_minutes} min`}.</p></details>
    {data.next_candidates.length > 0 && <div className="space-y-2"><h3 className="text-sm font-medium">Próximos assuntos sugeridos</h3>{data.next_candidates.slice(0, 3).map(c => <div key={c.id} className="border-t border-slate-700 py-3"><div className="flex flex-wrap items-center justify-between gap-3"><div className="min-w-0 break-words"><p className="text-xs text-slate-400">{c.discipline}</p><p>{c.title}</p></div><Button variant="outline" onClick={() => onStudy(c)}>Estudar</Button></div><details><summary className="cursor-pointer text-xs text-purple-300 py-3 min-h-[44px]">Por quê?</summary><p className="text-xs text-slate-400">{c.reasons.join(' · ')}. Sugestão; seu plano não foi alterado.</p></details></div>)}</div>}
    {data.next_session && <div className="flex flex-wrap items-center justify-between gap-3 border-y border-slate-700 py-4"><div><p className="text-xs text-purple-300">Próxima sessão · {data.next_session.date}</p><h3 className="font-medium">{data.next_session.name} · {data.next_session.minutes} min</h3></div><Button onClick={() => onStudy(data.next_session)}>Começar</Button></div>}
    <details><summary className="cursor-pointer py-3 min-h-[44px] text-sm">Conteúdo e estágios de aprendizagem</summary><div className="space-y-3">{data.syllabus_graph.topics.length === 0 && <p className="text-sm text-slate-400">Adicione conteúdo à preparação para acompanhar os assuntos.</p>}{data.syllabus_graph.topics.slice(0, visibleTopics).map(t => <div key={t.id} className="border-t border-slate-700 py-2 min-w-0"><p className="text-xs text-slate-500">{data.syllabus_graph.disciplines?.find(d => d.id === t.notebook_id)?.title}</p><p className="break-words text-sm">{t.title} · {stages[t.stage]}</p><p className="text-xs text-slate-400">{t.covered ? 'Contato registrado' : 'Contato não marcado'} · {t.mastery.samples} respostas individuais · {t.mastery.score == null ? 'domínio sem amostra' : `domínio estimado ${t.mastery.score}%`}</p></div>)}{visibleTopics < data.syllabus_graph.topics.length && <Button variant="outline" onClick={() => setVisibleTopics(n => n + 20)}>Mostrar mais assuntos</Button>}</div></details>
    <details><summary className="cursor-pointer py-3 min-h-[44px] text-sm">Perfil e evolução recente</summary><p className="text-sm text-slate-400">{data.candidate_model.completed_sessions || 0} sessões concluídas nos últimos 28 dias. Confiança da estimativa: {data.candidate_model.confidence || 'sem amostra'}.</p>{data.recent_trend?.map(w => <p key={w.start} className="text-xs text-slate-400 py-2">{w.start} a {w.end}: {w.minutes} min · {w.questions} respostas individuais · {w.accuracy == null ? 'sem acurácia medida' : `${w.accuracy}% de acertos`}</p>)}{data.required_pace.uncovered_topics_per_week != null && <p className="text-xs text-slate-400">Para contato com todo o conteúdo até a data: {data.required_pace.uncovered_topics_per_week} assuntos por semana. Assuntos têm tamanhos diferentes; não é previsão de domínio.</p>}</details>
    <details><summary className="cursor-pointer py-3 min-h-[44px] text-sm">Evidências dos indicadores</summary><p className="text-xs text-slate-400 mb-3">Até 100 registros recentes. Sessões, revisões e flashcards documentam atividade; o domínio usa respostas individuais.</p><ul className="space-y-2">{data.evidence_ledger.map(e => <li key={`${e.kind}:${e.id}`} className="text-xs break-words border-t border-slate-700 py-2">{kinds[e.kind]} · {e.at?.slice(0, 10)}{e.correct != null ? ` · ${e.correct ? 'acerto' : 'erro'}` : ''}{e.minutes != null ? ` · ${e.minutes} min` : ''} · {e.affects_mastery ? 'Usada no domínio' : 'Registro de atividade'}<span className="block text-slate-500">ID: {e.id}</span></li>)}</ul></details>
    <p className="text-xs text-slate-500">Calculado em {data.source_freshness.computed_at}. {data.source_freshness.official_source_checked_at ? `Última consulta bem-sucedida às fontes oficiais: ${new Date(data.source_freshness.official_source_checked_at).toLocaleString('pt-BR')}. Confira as mudanças no radar.` : 'Sem consulta bem-sucedida registrada para uma fonte oficial ativa.'}</p>
  </section>;
}
