import { useEffect, useState } from 'react';
import axios from 'axios';
import { Button } from '@/components/ui/button';
import { openSirius } from '@/lib/sirius-context';
const API = `${process.env.REACT_APP_BACKEND_URL || 'http://localhost:8000'}/api/study/v2`;
const names = { note: 'Nota', summary: 'Resumo da sessão', flashcard: 'Flashcard', link: 'Link externo', file: 'Arquivo enviado', edital: 'Edital analisado' };
const control = 'rounded-lg bg-slate-900 border border-slate-700 p-2 text-sm min-w-0';
export default function StudyLibrary({ programs, onNotebook, onAnalysis, onManage }) {
  const [program, setProgram] = useState(''), [notebook, setNotebook] = useState(''), [kind, setKind] = useState(''), [query, setQuery] = useState('');
  const [data, setData] = useState({ items: [], notebooks: [] }), [error, setError] = useState(''), [loading, setLoading] = useState(false);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(''); axios.get(`${API}/library`, { params: { program_id: program || undefined, notebook_id: notebook || undefined }, signal: controller.signal }).then(r => setData(r.data)).catch(() => { if (!controller.signal.aborted) setError('Não foi possível carregar a biblioteca.'); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [program, notebook]);
  const rows = (data.items || []).filter(i => (!kind || i.kind === kind) && `${i.title} ${i.excerpt || ''}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));
  return <section className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">Sua biblioteca</h2><p className="text-sm text-slate-400 mt-1">Materiais, notas e cartões, com a origem sempre visível.</p></div><Button variant="secondary" onClick={onManage}>Organizar matérias e materiais</Button></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2"><input aria-label="Buscar na biblioteca" className={control} value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar assunto ou material" /><select aria-label="Filtrar preparação" className={control} value={program} onChange={e => { setProgram(e.target.value); setNotebook(''); }}><option value="">Todas as preparações</option>{programs.map(p => <option key={p.program_id} value={p.program_id}>{p.name}</option>)}</select><select aria-label="Filtrar matéria" className={control} value={notebook} onChange={e => setNotebook(e.target.value)}><option value="">Todas as matérias</option>{(data.notebooks || []).map(n => <option key={n.notebook_id} value={n.notebook_id}>{n.name}</option>)}</select><select aria-label="Filtrar tipo de material" className={control} value={kind} onChange={e => setKind(e.target.value)}><option value="">Todos os tipos</option>{Object.entries(names).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div>{error && <p role="alert">{error}</p>}{loading && <p role="status">Carregando materiais…</p>}{!loading && !rows.length && <p className="py-6 text-slate-400">Nenhum material encontrado com esses filtros.</p>}
    <div className="divide-y divide-slate-800">{rows.map(item => <article className="py-4 space-y-2" key={item.id}><span className="text-xs text-purple-300">{names[item.kind]} · {item.provenance === 'external' ? 'Fonte externa, não oficial' : item.provenance === 'inferred' ? 'Leitura por IA' : item.provenance === 'extracted' ? 'Extraído, confira a fonte' : 'Conteúdo do usuário'}</span><h3 className="font-medium">{item.title}</h3>{item.excerpt && <details><summary className="text-xs cursor-pointer text-slate-400">Ler conteúdo</summary><p className="text-sm text-slate-300 whitespace-pre-wrap break-words mt-2">{item.excerpt}</p></details>}<div>{item.url ? <a href={item.url} target="_blank" rel="noopener noreferrer" className="text-sm text-sky-300">Abrir fonte externa ↗</a> : <Button variant="ghost" onClick={() => item.analysis_id ? onAnalysis(item.analysis_id) : item.attachment_id ? openSirius({ attachment_id: item.attachment_id, draft: `Resuma o arquivo ${item.title}.` }) : onNotebook(data.notebooks.find(n => n.notebook_id === item.notebook_id))}>{item.attachment_id ? 'Consultar com Sirius' : 'Abrir material'}</Button>}</div></article>)}</div>
  </section>;
}
