"""Progress is computed from owned completion counts, never generated by a model."""
def progress_score(raw):
    total = sum(raw.get(key, 0) for key in ('tasks_done', 'habits_done', 'tasks_pending', 'habits_pending'))
    completed = raw.get('tasks_done', 0) + raw.get('habits_done', 0)
    return round(completed / total * 100) if total else 0
