"""persist transactional XP entries for analytics

Revision ID: 060d04832219
Revises: 9b0a2c5d026b
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '060d04832219'
down_revision: Union[str, Sequence[str], None] = '9b0a2c5d026b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xp_entries',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount != 0', name=op.f('ck_xp_entries_nonzero')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_xp_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_entries'))
    )
    op.create_index('ix_xp_entries_owner_date', 'xp_entries', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_xp_entries_user_id'), 'xp_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xp_entries_user_id'), table_name='xp_entries')
    op.drop_index('ix_xp_entries_owner_date', table_name='xp_entries')
    op.drop_table('xp_entries')
    # ### end Alembic commands ###
