"""finance purchase installments invoices and monthly bills

Revision ID: 0e61828b3519
Revises: d18c704a928e
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0e61828b3519'
down_revision: Union[str, Sequence[str], None] = 'd18c704a928e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_invoices',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_card_invoices_amount')),
    sa.ForeignKeyConstraint(['user_id', 'card_id'], ['credit_cards.user_id', 'credit_cards.id'], name=op.f('fk_card_invoices_user_id_credit_cards'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_card_invoices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_invoices')),
    sa.UniqueConstraint('user_id', 'card_id', 'month', name=op.f('uq_card_invoices_user_id_card_id_month'))
    )
    op.create_index(op.f('ix_card_invoices_user_id'), 'card_invoices', ['user_id'], unique=False)
    op.create_table('card_purchases',
    sa.Column('card_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('first_month', sa.Date(), nullable=False),
    sa.Column('start_month', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0 AND installments BETWEEN 1 AND 120', name=op.f('ck_card_purchases_amount_installments')),
    sa.ForeignKeyConstraint(['user_id', 'card_id'], ['credit_cards.user_id', 'credit_cards.id'], name=op.f('fk_card_purchases_user_id_credit_cards'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_card_purchases_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_purchases')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_card_purchases_user_id_id'))
    )
    op.create_index(op.f('ix_card_purchases_user_id'), 'card_purchases', ['user_id'], unique=False)
    op.create_table('financial_projections',
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('projection_type', sa.String(), nullable=False),
    sa.Column('is_fixed', sa.Boolean(), nullable=False),
    sa.Column('repeat_count', sa.Integer(), nullable=True),
    sa.Column('remaining_repeats', sa.Integer(), nullable=True),
    sa.Column('purchase_id', sa.Uuid(), nullable=True),
    sa.Column('installment_number', sa.Integer(), nullable=True),
    sa.Column('total_installments', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_financial_projections_amount')),
    sa.ForeignKeyConstraint(['user_id', 'card_id'], ['credit_cards.user_id', 'credit_cards.id'], name=op.f('fk_financial_projections_user_id_credit_cards'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'purchase_id'], ['card_purchases.user_id', 'card_purchases.id'], name=op.f('fk_financial_projections_user_id_card_purchases'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_financial_projections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_projections')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_financial_projections_user_id_id'))
    )
    op.create_index(op.f('ix_financial_projections_user_id'), 'financial_projections', ['user_id'], unique=False)
    op.create_index('ix_projections_owner_month', 'financial_projections', ['user_id', 'month'], unique=False)
    op.create_table('monthly_bills',
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('projection_id', sa.Uuid(), nullable=True),
    sa.Column('card_id', sa.Uuid(), nullable=True),
    sa.Column('installment_info', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_monthly_bills_amount')),
    sa.ForeignKeyConstraint(['user_id', 'card_id'], ['credit_cards.user_id', 'credit_cards.id'], name=op.f('fk_monthly_bills_user_id_credit_cards'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'projection_id'], ['financial_projections.user_id', 'financial_projections.id'], name=op.f('fk_monthly_bills_user_id_financial_projections'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_monthly_bills_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_bills')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_monthly_bills_user_id_id')),
    sa.UniqueConstraint('user_id', 'projection_id', name=op.f('uq_monthly_bills_user_id_projection_id'))
    )
    op.create_index('ix_bills_owner_month', 'monthly_bills', ['user_id', 'month'], unique=False)
    op.create_index(op.f('ix_monthly_bills_user_id'), 'monthly_bills', ['user_id'], unique=False)
    op.add_column('finance_categories', sa.Column('icon', sa.String(), nullable=False, server_default=''))
    op.add_column('finance_categories', sa.Column('color', sa.String(), nullable=False, server_default=''))
    op.alter_column('finance_categories', 'icon', server_default=None)
    op.alter_column('finance_categories', 'color', server_default=None)
    op.add_column('financial_transactions', sa.Column('purchase_id', sa.Uuid(), nullable=True))
    op.add_column('financial_transactions', sa.Column('bill_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_financial_transactions_user_id_bill_id'), 'financial_transactions', ['user_id', 'bill_id'])
    op.create_unique_constraint(op.f('uq_financial_transactions_user_id_id'), 'financial_transactions', ['user_id', 'id'])
    op.create_foreign_key(op.f('fk_financial_transactions_user_id_card_purchases'), 'financial_transactions', 'card_purchases', ['user_id', 'purchase_id'], ['user_id', 'id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_financial_transactions_user_id_monthly_bills'), 'financial_transactions', 'monthly_bills', ['user_id', 'bill_id'], ['user_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_financial_transactions_user_id_monthly_bills'), 'financial_transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_financial_transactions_user_id_card_purchases'), 'financial_transactions', type_='foreignkey')
    op.drop_constraint(op.f('uq_financial_transactions_user_id_id'), 'financial_transactions', type_='unique')
    op.drop_constraint(op.f('uq_financial_transactions_user_id_bill_id'), 'financial_transactions', type_='unique')
    op.drop_column('financial_transactions', 'bill_id')
    op.drop_column('financial_transactions', 'purchase_id')
    op.drop_column('finance_categories', 'color')
    op.drop_column('finance_categories', 'icon')
    op.drop_index(op.f('ix_monthly_bills_user_id'), table_name='monthly_bills')
    op.drop_index('ix_bills_owner_month', table_name='monthly_bills')
    op.drop_table('monthly_bills')
    op.drop_index('ix_projections_owner_month', table_name='financial_projections')
    op.drop_index(op.f('ix_financial_projections_user_id'), table_name='financial_projections')
    op.drop_table('financial_projections')
    op.drop_index(op.f('ix_card_purchases_user_id'), table_name='card_purchases')
    op.drop_table('card_purchases')
    op.drop_index(op.f('ix_card_invoices_user_id'), table_name='card_invoices')
    op.drop_table('card_invoices')
    # ### end Alembic commands ###
