"""track reviewed analysis revisions

Revision ID: 11423c288614
Revises: 9f463181b69a
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '11423c288614'
down_revision: Union[str, Sequence[str], None] = '9f463181b69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edital_analyses', sa.Column('revision', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('edital_analyses', 'revision', server_default=None)
    op.add_column('edital_analyses', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edital_analyses', 'reviewed_at')
    op.drop_column('edital_analyses', 'revision')
    # ### end Alembic commands ###
