"""Typed Telegram links codes and update receipts

Revision ID: 126b856daebb
Revises: 7293cc85b93b
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '126b856daebb'
down_revision: Union[str, Sequence[str], None] = '7293cc85b93b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_link_codes',
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_link_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_link_codes')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_telegram_link_codes_code_hash')),
    sa.UniqueConstraint('user_id', name=op.f('uq_telegram_link_codes_user_id'))
    )
    op.create_index(op.f('ix_telegram_link_codes_user_id'), 'telegram_link_codes', ['user_id'], unique=False)
    op.create_table('telegram_links',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_name', sa.String(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_links')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_telegram_links_chat_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_telegram_links_user_id'))
    )
    op.create_index(op.f('ix_telegram_links_user_id'), 'telegram_links', ['user_id'], unique=False)
    op.create_table('telegram_updates',
    sa.Column('update_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('lease_token', sa.Uuid(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_updates_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('update_id', name=op.f('pk_telegram_updates'))
    )
    op.create_index(op.f('ix_telegram_updates_user_id'), 'telegram_updates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_updates_user_id'), table_name='telegram_updates')
    op.drop_table('telegram_updates')
    op.drop_index(op.f('ix_telegram_links_user_id'), table_name='telegram_links')
    op.drop_table('telegram_links')
    op.drop_index(op.f('ix_telegram_link_codes_user_id'), table_name='telegram_link_codes')
    op.drop_table('telegram_link_codes')
    # ### end Alembic commands ###
