"""persist study assignments and daily completion facts

Revision ID: 13ef5c5fbe1f
Revises: ffe3963e1090
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '13ef5c5fbe1f'
down_revision: Union[str, Sequence[str], None] = 'ffe3963e1090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_tasks',
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notebook_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('recurrence', sa.String(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('reminder', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low','medium','high')", name=op.f('ck_study_tasks_priority')),
    sa.CheckConstraint("recurrence IN ('once','daily','weekly','monthly')", name=op.f('ck_study_tasks_recurrence')),
    sa.CheckConstraint('estimated_minutes >= 0 AND actual_minutes >= 0', name=op.f('ck_study_tasks_minutes')),
    sa.ForeignKeyConstraint(['user_id', 'notebook_id'], ['study_notebooks.user_id', 'study_notebooks.id'], name=op.f('fk_study_tasks_user_id_study_notebooks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_tasks')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_study_tasks_user_id_id'))
    )
    op.create_index(op.f('ix_study_tasks_user_id'), 'study_tasks', ['user_id'], unique=False)
    op.create_table('study_task_checks',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'task_id'], ['study_tasks.user_id', 'study_tasks.id'], name=op.f('fk_study_task_checks_user_id_study_tasks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_task_checks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_task_checks')),
    sa.UniqueConstraint('user_id', 'task_id', 'date', name=op.f('uq_study_task_checks_user_id_task_id_date'))
    )
    op.create_index(op.f('ix_study_task_checks_user_id'), 'study_task_checks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_task_checks_user_id'), table_name='study_task_checks')
    op.drop_table('study_task_checks')
    op.drop_index(op.f('ix_study_tasks_user_id'), table_name='study_tasks')
    op.drop_table('study_tasks')
    # ### end Alembic commands ###
