"""normalize nutrition plans and shopping lists

Revision ID: 1d41972a807e
Revises: e8f211413453
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1d41972a807e'
down_revision: Union[str, Sequence[str], None] = 'e8f211413453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_plans',
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('diet_type', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source_filename', sa.String(), nullable=True),
    sa.Column('daily_calories', sa.Float(), nullable=False),
    sa.Column('daily_protein', sa.Float(), nullable=False),
    sa.Column('daily_carbs', sa.Float(), nullable=False),
    sa.Column('daily_fat', sa.Float(), nullable=False),
    sa.Column('daily_fiber', sa.Float(), nullable=False),
    sa.Column('restrictions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('tips', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('diet','generated','imported')", name=op.f('ck_nutrition_plans_kind')),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name=op.f('ck_nutrition_plans_dates')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_nutrition_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_plans')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_nutrition_plans_user_id_id'))
    )
    op.create_index('ix_nutrition_plans_owner_created', 'nutrition_plans', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_nutrition_plans_user_id'), 'nutrition_plans', ['user_id'], unique=False)
    op.create_table('nutrition_plan_days',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('day_name', sa.String(), nullable=False),
    sa.Column('day_label', sa.String(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'plan_id'], ['nutrition_plans.user_id', 'nutrition_plans.id'], name=op.f('fk_nutrition_plan_days_user_id_nutrition_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_nutrition_plan_days_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_plan_days')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_nutrition_plan_days_user_id_id')),
    sa.UniqueConstraint('user_id', 'plan_id', 'position', name=op.f('uq_nutrition_plan_days_user_id_plan_id_position'))
    )
    op.create_index(op.f('ix_nutrition_plan_days_user_id'), 'nutrition_plan_days', ['user_id'], unique=False)
    op.create_table('plan_shopping_items',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'plan_id'], ['nutrition_plans.user_id', 'nutrition_plans.id'], name=op.f('fk_plan_shopping_items_user_id_nutrition_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_plan_shopping_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_shopping_items')),
    sa.UniqueConstraint('user_id', 'plan_id', 'position', name=op.f('uq_plan_shopping_items_user_id_plan_id_position'))
    )
    op.create_index(op.f('ix_plan_shopping_items_user_id'), 'plan_shopping_items', ['user_id'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'plan_id'], ['nutrition_plans.user_id', 'nutrition_plans.id'], name=op.f('fk_shopping_lists_user_id_nutrition_plans')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shopping_lists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_lists')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_shopping_lists_user_id_id'))
    )
    op.create_index('ix_shopping_lists_owner_created', 'shopping_lists', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_shopping_lists_user_id'), 'shopping_lists', ['user_id'], unique=False)
    op.create_table('planned_meals',
    sa.Column('day_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('preparation', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'day_id'], ['nutrition_plan_days.user_id', 'nutrition_plan_days.id'], name=op.f('fk_planned_meals_user_id_nutrition_plan_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_planned_meals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planned_meals')),
    sa.UniqueConstraint('user_id', 'day_id', 'position', name=op.f('uq_planned_meals_user_id_day_id_position')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_planned_meals_user_id_id'))
    )
    op.create_index(op.f('ix_planned_meals_user_id'), 'planned_meals', ['user_id'], unique=False)
    op.create_table('shopping_items',
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'list_id'], ['shopping_lists.user_id', 'shopping_lists.id'], name=op.f('fk_shopping_items_user_id_shopping_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shopping_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_items')),
    sa.UniqueConstraint('user_id', 'list_id', 'position', name=op.f('uq_shopping_items_user_id_list_id_position'))
    )
    op.create_index(op.f('ix_shopping_items_user_id'), 'shopping_items', ['user_id'], unique=False)
    op.create_table('planned_foods',
    sa.Column('meal_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'meal_id'], ['planned_meals.user_id', 'planned_meals.id'], name=op.f('fk_planned_foods_user_id_planned_meals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_planned_foods_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planned_foods')),
    sa.UniqueConstraint('user_id', 'meal_id', 'position', name=op.f('uq_planned_foods_user_id_meal_id_position'))
    )
    op.create_index(op.f('ix_planned_foods_user_id'), 'planned_foods', ['user_id'], unique=False)
    op.add_column('meals', sa.Column('reported_calories', sa.Float(), nullable=True))
    op.add_column('meals', sa.Column('reported_protein', sa.Float(), nullable=True))
    op.add_column('meals', sa.Column('reported_carbs', sa.Float(), nullable=True))
    op.add_column('meals', sa.Column('reported_fat', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'reported_fat')
    op.drop_column('meals', 'reported_carbs')
    op.drop_column('meals', 'reported_protein')
    op.drop_column('meals', 'reported_calories')
    op.drop_index(op.f('ix_planned_foods_user_id'), table_name='planned_foods')
    op.drop_table('planned_foods')
    op.drop_index(op.f('ix_shopping_items_user_id'), table_name='shopping_items')
    op.drop_table('shopping_items')
    op.drop_index(op.f('ix_planned_meals_user_id'), table_name='planned_meals')
    op.drop_table('planned_meals')
    op.drop_index(op.f('ix_shopping_lists_user_id'), table_name='shopping_lists')
    op.drop_index('ix_shopping_lists_owner_created', table_name='shopping_lists')
    op.drop_table('shopping_lists')
    op.drop_index(op.f('ix_plan_shopping_items_user_id'), table_name='plan_shopping_items')
    op.drop_table('plan_shopping_items')
    op.drop_index(op.f('ix_nutrition_plan_days_user_id'), table_name='nutrition_plan_days')
    op.drop_table('nutrition_plan_days')
    op.drop_index(op.f('ix_nutrition_plans_user_id'), table_name='nutrition_plans')
    op.drop_index('ix_nutrition_plans_owner_created', table_name='nutrition_plans')
    op.drop_table('nutrition_plans')
    # ### end Alembic commands ###
