"""typed assistant insights and event leases

Revision ID: 221a3e378a66
Revises: 8721bc0c9cf9
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '221a3e378a66'
down_revision: Union[str, Sequence[str], None] = '8721bc0c9cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insights',
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("feedback IS NULL OR feedback IN ('dismiss','snooze','never','helpful')", name=op.f('ck_ai_insights_feedback')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_insights_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_insights')),
    sa.UniqueConstraint('user_id', 'rule', 'date', name=op.f('uq_ai_insights_user_id_rule_date'))
    )
    op.create_index(op.f('ix_ai_insights_user_id'), 'ai_insights', ['user_id'], unique=False)
    op.create_index('ix_insights_owner_date', 'ai_insights', ['user_id', 'date'], unique=False)
    op.add_column('ai_events', sa.Column('dedup_key', sa.String(), nullable=True))
    op.add_column('ai_events', sa.Column('lease_token', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_ai_events_user_id_dedup_key'), 'ai_events', ['user_id', 'dedup_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ai_events_user_id_dedup_key'), 'ai_events', type_='unique')
    op.drop_column('ai_events', 'lease_token')
    op.drop_column('ai_events', 'dedup_key')
    op.drop_index('ix_insights_owner_date', table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_user_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    # ### end Alembic commands ###
