"""persist body measurements and saved workout insights

Revision ID: 32afa15613bd
Revises: 6460b39c74a1
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '32afa15613bd'
down_revision: Union[str, Sequence[str], None] = '6460b39c74a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_measurements',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('muscle_mass_kg', sa.Float(), nullable=True),
    sa.Column('bone_mass_kg', sa.Float(), nullable=True),
    sa.Column('water_percentage', sa.Float(), nullable=True),
    sa.Column('visceral_fat', sa.Integer(), nullable=True),
    sa.Column('metabolic_age', sa.Integer(), nullable=True),
    sa.Column('bmr_kcal', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('neck_cm', sa.Float(), nullable=True),
    sa.Column('shoulders_cm', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('abdomen_cm', sa.Float(), nullable=True),
    sa.Column('hips_cm', sa.Float(), nullable=True),
    sa.Column('left_arm_cm', sa.Float(), nullable=True),
    sa.Column('right_arm_cm', sa.Float(), nullable=True),
    sa.Column('left_forearm_cm', sa.Float(), nullable=True),
    sa.Column('right_forearm_cm', sa.Float(), nullable=True),
    sa.Column('left_thigh_cm', sa.Float(), nullable=True),
    sa.Column('right_thigh_cm', sa.Float(), nullable=True),
    sa.Column('left_calf_cm', sa.Float(), nullable=True),
    sa.Column('right_calf_cm', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('height_cm IS NULL OR height_cm > 0', name=op.f('ck_body_measurements_height')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_body_measurements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_measurements'))
    )
    op.create_index(op.f('ix_body_measurements_user_id'), 'body_measurements', ['user_id'], unique=False)
    op.create_index('ix_measurements_owner_date', 'body_measurements', ['user_id', 'date'], unique=False)
    op.create_table('workout_insights',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('total_workouts', sa.Integer(), nullable=False),
    sa.Column('has_measurements', sa.Boolean(), nullable=False),
    sa.Column('workout_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_insights_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_insights'))
    )
    op.create_index('ix_workout_insights_owner_created', 'workout_insights', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_workout_insights_user_id'), 'workout_insights', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_insights_user_id'), table_name='workout_insights')
    op.drop_index('ix_workout_insights_owner_created', table_name='workout_insights')
    op.drop_table('workout_insights')
    op.drop_index('ix_measurements_owner_date', table_name='body_measurements')
    op.drop_index(op.f('ix_body_measurements_user_id'), table_name='body_measurements')
    op.drop_table('body_measurements')
    # ### end Alembic commands ###
