"""persist focus break duration with study sessions

Revision ID: 3968deb85ca6
Revises: a0e1aba8b22c
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3968deb85ca6'
down_revision: Union[str, Sequence[str], None] = 'a0e1aba8b22c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_sessions', sa.Column('break_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_sessions', 'break_minutes')
    # ### end Alembic commands ###
