"""relational questions exams and attempt evidence

Revision ID: 3b22081c7fa1
Revises: b74fa82e3a67
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3b22081c7fa1'
down_revision: Union[str, Sequence[str], None] = 'b74fa82e3a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('program_id', sa.Uuid(), nullable=True),
    sa.Column('notebook_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('blueprint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'notebook_id'], ['study_notebooks.user_id', 'study_notebooks.id'], name=op.f('fk_exams_user_id_study_notebooks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'program_id'], ['study_programs.user_id', 'study_programs.id'], name=op.f('fk_exams_user_id_study_programs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exams_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exams')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_exams_user_id_id'))
    )
    op.create_index(op.f('ix_exams_user_id'), 'exams', ['user_id'], unique=False)
    op.create_table('exam_attempts',
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('scoring_version', sa.String(), nullable=False),
    sa.Column('result_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('score BETWEEN 0 AND 100 AND duration_seconds >= 0', name=op.f('ck_exam_attempts_score_duration')),
    sa.ForeignKeyConstraint(['user_id', 'exam_id'], ['exams.user_id', 'exams.id'], name=op.f('fk_exam_attempts_user_id_exams'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exam_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_attempts')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_exam_attempts_user_id_id'))
    )
    op.create_index('ix_exam_attempt_owner_completed', 'exam_attempts', ['user_id', 'completed_at'], unique=False)
    op.create_index(op.f('ix_exam_attempts_user_id'), 'exam_attempts', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('notebook_id', sa.Uuid(), nullable=True),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'notebook_id'], ['study_notebooks.user_id', 'study_notebooks.id'], name=op.f('fk_questions_user_id_study_notebooks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'topic_id'], ['study_topics.user_id', 'study_topics.id'], name=op.f('fk_questions_user_id_study_topics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_questions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_questions_user_id_id'))
    )
    op.create_index(op.f('ix_questions_user_id'), 'questions', ['user_id'], unique=False)
    op.create_table('exam_questions',
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('weight > 0 AND position >= 0', name=op.f('ck_exam_questions_weight_position')),
    sa.ForeignKeyConstraint(['user_id', 'exam_id'], ['exams.user_id', 'exams.id'], name=op.f('fk_exam_questions_user_id_exams'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'question_id'], ['questions.user_id', 'questions.id'], name=op.f('fk_exam_questions_user_id_questions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exam_questions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_questions')),
    sa.UniqueConstraint('user_id', 'exam_id', 'position', name=op.f('uq_exam_questions_user_id_exam_id_position'))
    )
    op.create_index(op.f('ix_exam_questions_user_id'), 'exam_questions', ['user_id'], unique=False)
    op.add_column('question_attempts', sa.Column('exam_attempt_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_question_attempts_user_id_questions'), 'question_attempts', 'questions', ['user_id', 'question_id'], ['user_id', 'id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_question_attempts_user_id_exam_attempts'), 'question_attempts', 'exam_attempts', ['user_id', 'exam_attempt_id'], ['user_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_question_attempts_user_id_exam_attempts'), 'question_attempts', type_='foreignkey')
    op.drop_constraint(op.f('fk_question_attempts_user_id_questions'), 'question_attempts', type_='foreignkey')
    op.drop_column('question_attempts', 'exam_attempt_id')
    op.drop_index(op.f('ix_exam_questions_user_id'), table_name='exam_questions')
    op.drop_table('exam_questions')
    op.drop_index(op.f('ix_questions_user_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_exam_attempts_user_id'), table_name='exam_attempts')
    op.drop_index('ix_exam_attempt_owner_completed', table_name='exam_attempts')
    op.drop_table('exam_attempts')
    op.drop_index(op.f('ix_exams_user_id'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
