"""owned achievements and weekly challenge rewards

Revision ID: 4125068ff630
Revises: 221a3e378a66
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4125068ff630'
down_revision: Union[str, Sequence[str], None] = '221a3e378a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements')),
    sa.UniqueConstraint('user_id', 'key', name=op.f('uq_achievements_user_id_key'))
    )
    op.create_index('ix_achievements_owner_unlocked', 'achievements', ['user_id', 'unlocked_at'], unique=False)
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.create_table('weekly_challenges',
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('xp_reward >= 0 AND week_end > week_start', name=op.f('ck_weekly_challenges_reward_period')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weekly_challenges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_challenges')),
    sa.UniqueConstraint('user_id', 'week_start', 'kind', name=op.f('uq_weekly_challenges_user_id_week_start_kind'))
    )
    op.create_index(op.f('ix_weekly_challenges_user_id'), 'weekly_challenges', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_challenges_user_id'), table_name='weekly_challenges')
    op.drop_table('weekly_challenges')
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.drop_index('ix_achievements_owner_unlocked', table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
