"""preserve exam area and archive history

Revision ID: 446593f7d365
Revises: aaf789704647
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '446593f7d365'
down_revision: Union[str, Sequence[str], None] = 'aaf789704647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exams', sa.Column('area_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_exams_user_id_study_areas'), 'exams', 'study_areas', ['user_id', 'area_id'], ['user_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_exams_user_id_study_areas'), 'exams', type_='foreignkey')
    op.drop_column('exams', 'area_id')
    op.drop_column('exams', 'archived_at')
    # ### end Alembic commands ###
