"""normalized conversation leases messages and receipts

Revision ID: 4e16ba167d61
Revises: 93726080ad93
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4e16ba167d61'
down_revision: Union[str, Sequence[str], None] = '93726080ad93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversation_receipts',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('message_hash', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'conversation_id'], ['ai_conversations.user_id', 'ai_conversations.id'], name=op.f('fk_ai_conversation_receipts_user_id_ai_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_conversation_receipts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversation_receipts')),
    sa.UniqueConstraint('conversation_id', 'request_id', name=op.f('uq_ai_conversation_receipts_conversation_id_request_id'))
    )
    op.create_index(op.f('ix_ai_conversation_receipts_user_id'), 'ai_conversation_receipts', ['user_id'], unique=False)
    op.add_column('ai_conversations', sa.Column('external_id', sa.String(), nullable=False))
    op.add_column('ai_conversations', sa.Column('lease_token', sa.Uuid(), nullable=True))
    op.add_column('ai_conversations', sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_conversations', sa.Column('last_sequence', sa.Integer(), nullable=False))
    op.add_column('ai_conversations', sa.Column('context_from', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_ai_conversations_user_id_external_id'), 'ai_conversations', ['user_id', 'external_id'])
    op.create_check_constraint(op.f('ck_ai_conversations_sequence'), 'ai_conversations', 'last_sequence >= 0 AND context_from >= 1')
    op.add_column('ai_messages', sa.Column('sequence', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_ai_messages_conversation_id_sequence'), 'ai_messages', ['conversation_id', 'sequence'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ai_messages_conversation_id_sequence'), 'ai_messages', type_='unique')
    op.drop_column('ai_messages', 'sequence')
    op.drop_constraint(op.f('uq_ai_conversations_user_id_external_id'), 'ai_conversations', type_='unique')
    op.drop_constraint(op.f('ck_ai_conversations_sequence'), 'ai_conversations', type_='check')
    op.drop_column('ai_conversations', 'context_from')
    op.drop_column('ai_conversations', 'last_sequence')
    op.drop_column('ai_conversations', 'lease_until')
    op.drop_column('ai_conversations', 'lease_token')
    op.drop_column('ai_conversations', 'external_id')
    op.drop_index(op.f('ix_ai_conversation_receipts_user_id'), table_name='ai_conversation_receipts')
    op.drop_table('ai_conversation_receipts')
    # ### end Alembic commands ###
