"""persist edital queue with object storage references

Revision ID: 5790e0d50771
Revises: 11423c288614
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5790e0d50771'
down_revision: Union[str, Sequence[str], None] = '11423c288614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edital_jobs',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('force', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','failed','completed')", name=op.f('ck_edital_jobs_status')),
    sa.ForeignKeyConstraint(['analysis_id'], ['edital_analyses.id'], name=op.f('fk_edital_jobs_analysis_id_edital_analyses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_edital_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edital_jobs'))
    )
    op.create_index('ix_edital_jobs_status_created', 'edital_jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_edital_jobs_user_id'), 'edital_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edital_jobs_user_id'), table_name='edital_jobs')
    op.drop_index('ix_edital_jobs_status_created', table_name='edital_jobs')
    op.drop_table('edital_jobs')
    # ### end Alembic commands ###
