"""persist daily workout checklists and completion links

Revision ID: 6460b39c74a1
Revises: 99b09cc30936
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6460b39c74a1'
down_revision: Union[str, Sequence[str], None] = '99b09cc30936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_workout_status',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('log_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['workout_logs.id'], name=op.f('fk_daily_workout_status_log_id_workout_logs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id', 'log_id'], ['workout_logs.user_id', 'workout_logs.id'], name=op.f('fk_daily_workout_status_user_id_workout_logs'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['user_id', 'plan_id'], ['workout_plans.user_id', 'workout_plans.id'], name=op.f('fk_daily_workout_status_user_id_workout_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_workout_status_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_workout_status')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_daily_workout_status_user_id_id')),
    sa.UniqueConstraint('user_id', 'plan_id', 'date', name=op.f('uq_daily_workout_status_user_id_plan_id_date'))
    )
    op.create_index(op.f('ix_daily_workout_status_user_id'), 'daily_workout_status', ['user_id'], unique=False)
    op.create_table('daily_workout_checks',
    sa.Column('status_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('exercise_index >= 0', name=op.f('ck_daily_workout_checks_index')),
    sa.ForeignKeyConstraint(['user_id', 'status_id'], ['daily_workout_status.user_id', 'daily_workout_status.id'], name=op.f('fk_daily_workout_checks_user_id_daily_workout_status'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_workout_checks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_workout_checks')),
    sa.UniqueConstraint('user_id', 'status_id', 'exercise_index', name=op.f('uq_daily_workout_checks_user_id_status_id_exercise_index'))
    )
    op.create_index(op.f('ix_daily_workout_checks_user_id'), 'daily_workout_checks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_workout_checks_user_id'), table_name='daily_workout_checks')
    op.drop_table('daily_workout_checks')
    op.drop_index(op.f('ix_daily_workout_status_user_id'), table_name='daily_workout_status')
    op.drop_table('daily_workout_status')
    # ### end Alembic commands ###
