"""identity planning finance studies agent foundation

Revision ID: 65872ffe48c9
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '65872ffe48c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('xp >= 0', name=op.f('ck_users_xp_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email_normalized', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('activity_receipts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('request_key', sa.String(length=128), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_receipts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_receipts')),
    sa.UniqueConstraint('user_id', 'request_key', name=op.f('uq_activity_receipts_user_id_request_key'))
    )
    op.create_table('ai_actions',
    sa.Column('request_fingerprint', sa.String(), nullable=False),
    sa.Column('tool', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('autonomy', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','confirmed','executed','cancelled','expired')", name=op.f('ck_ai_actions_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_actions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_actions')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_ai_actions_user_id_id')),
    sa.UniqueConstraint('user_id', 'request_fingerprint', name=op.f('uq_ai_actions_user_id_request_fingerprint'))
    )
    op.create_index('ix_actions_owner_status_expiry', 'ai_actions', ['user_id', 'status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_ai_actions_user_id'), 'ai_actions', ['user_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_conversations')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_ai_conversations_user_id_id'))
    )
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_index('ix_conversations_owner_updated', 'ai_conversations', ['user_id', 'updated_at'], unique=False)
    op.create_index('uq_conversation_primary', 'ai_conversations', ['user_id'], unique=True, postgresql_where=sa.text('"primary" IS true'))
    op.create_table('ai_events',
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_events'))
    )
    op.create_index(op.f('ix_ai_events_user_id'), 'ai_events', ['user_id'], unique=False)
    op.create_index('ix_events_owner_created', 'ai_events', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_events_status_lease', 'ai_events', ['status', 'lease_until'], unique=False)
    op.create_table('ai_memories',
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_memories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_memories')),
    sa.UniqueConstraint('user_id', 'kind', 'content_hash', name=op.f('uq_ai_memories_user_id_kind_content_hash'))
    )
    op.create_index(op.f('ix_ai_memories_user_id'), 'ai_memories', ['user_id'], unique=False)
    op.create_table('ai_preferences',
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_ai_preferences_user_id'))
    )
    op.create_index(op.f('ix_ai_preferences_user_id'), 'ai_preferences', ['user_id'], unique=False)
    op.create_table('ai_usage',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_usage_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage'))
    )
    op.create_index('ix_ai_usage_owner_created', 'ai_usage', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_user_id'), 'ai_usage', ['user_id'], unique=False)
    op.create_table('budgets',
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"limit" >= 0', name=op.f('ck_budgets_limit')),
    sa.CheckConstraint('EXTRACT(DAY FROM month) = 1', name=op.f('ck_budgets_month_start')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_budgets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
    sa.UniqueConstraint('user_id', 'category', 'month', name=op.f('uq_budgets_user_id_category_month'))
    )
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at >= start_at', name=op.f('ck_calendar_events_interval')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendar_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_events'))
    )
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_index('ix_calendar_owner_start', 'calendar_events', ['user_id', 'start_at'], unique=False)
    op.create_table('credit_cards',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_day', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"limit" >= 0', name=op.f('ck_credit_cards_limit')),
    sa.CheckConstraint('closing_day BETWEEN 1 AND 31', name=op.f('ck_credit_cards_closing_day')),
    sa.CheckConstraint('due_day BETWEEN 1 AND 31', name=op.f('ck_credit_cards_due_day')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_cards_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_cards')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_credit_cards_user_id_id'))
    )
    op.create_index(op.f('ix_credit_cards_user_id'), 'credit_cards', ['user_id'], unique=False)
    op.create_table('files',
    sa.Column('storage_provider', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("storage_key IS NOT NULL OR storage_provider = 'metadata_only'", name=op.f('ck_files_storage_reference')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_files_size')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_files_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_files_user_id_id')),
    sa.UniqueConstraint('user_id', 'sha256', name=op.f('uq_files_user_id_sha256'))
    )
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.create_table('finance_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("type IN ('income','expense')", name=op.f('ck_finance_categories_type')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_finance_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_categories')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_finance_categories_user_id_id')),
    sa.UniqueConstraint('user_id', 'name', 'type', name=op.f('uq_finance_categories_user_id_name_type'))
    )
    op.create_index(op.f('ix_finance_categories_user_id'), 'finance_categories', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('sprint_duration', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name=op.f('ck_goals_progress')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_goals_user_id_id'))
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('habits',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_habits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habits')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_habits_user_id_id'))
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('study_areas',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_areas_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_areas')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_study_areas_user_id_id'))
    )
    op.create_index(op.f('ix_study_areas_user_id'), 'study_areas', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('recurrence', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low','medium','high')", name=op.f('ck_tasks_priority')),
    sa.CheckConstraint("recurrence IN ('once','daily','weekly','monthly')", name=op.f('ck_tasks_recurrence')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_tasks_user_id_id'))
    )
    op.create_index('ix_tasks_owner_date', 'tasks', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('ai_action_audit',
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('tool', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'action_id'], ['ai_actions.user_id', 'ai_actions.id'], name=op.f('fk_ai_action_audit_user_id_ai_actions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_action_audit_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_action_audit'))
    )
    op.create_index(op.f('ix_ai_action_audit_user_id'), 'ai_action_audit', ['user_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant','system','tool')", name=op.f('ck_ai_messages_role')),
    sa.ForeignKeyConstraint(['user_id', 'conversation_id'], ['ai_conversations.user_id', 'ai_conversations.id'], name=op.f('fk_ai_messages_user_id_ai_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_messages'))
    )
    op.create_index(op.f('ix_ai_messages_user_id'), 'ai_messages', ['user_id'], unique=False)
    op.create_index('ix_messages_conversation_created', 'ai_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('edital_analyses',
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('analysis_version', sa.String(), nullable=False),
    sa.Column('structured_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'file_id'], ['files.user_id', 'files.id'], name=op.f('fk_edital_analyses_user_id_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_edital_analyses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edital_analyses')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_edital_analyses_user_id_id'))
    )
    op.create_index('ix_analysis_owner_hash_version', 'edital_analyses', ['user_id', 'content_hash', 'analysis_version'], unique=False)
    op.create_index(op.f('ix_edital_analyses_user_id'), 'edital_analyses', ['user_id'], unique=False)
    op.create_table('financial_transactions',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('income','expense')", name=op.f('ck_financial_transactions_type')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_financial_transactions_amount')),
    sa.ForeignKeyConstraint(['user_id', 'category_id'], ['finance_categories.user_id', 'finance_categories.id'], name=op.f('fk_financial_transactions_user_id_finance_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_financial_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_transactions'))
    )
    op.create_index(op.f('ix_financial_transactions_user_id'), 'financial_transactions', ['user_id'], unique=False)
    op.create_index('ix_transactions_owner_date', 'financial_transactions', ['user_id', 'date'], unique=False)
    op.create_table('goal_checks',
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'goal_id'], ['goals.user_id', 'goals.id'], name=op.f('fk_goal_checks_user_id_goals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goal_checks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_checks')),
    sa.UniqueConstraint('user_id', 'goal_id', 'date', name=op.f('uq_goal_checks_user_id_goal_id_date'))
    )
    op.create_index(op.f('ix_goal_checks_user_id'), 'goal_checks', ['user_id'], unique=False)
    op.create_table('habit_checks',
    sa.Column('habit_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'habit_id'], ['habits.user_id', 'habits.id'], name=op.f('fk_habit_checks_user_id_habits'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_habit_checks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habit_checks')),
    sa.UniqueConstraint('user_id', 'habit_id', 'date', name=op.f('uq_habit_checks_user_id_habit_id_date'))
    )
    op.create_index(op.f('ix_habit_checks_user_id'), 'habit_checks', ['user_id'], unique=False)
    op.create_table('study_programs',
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','completed','paused')", name=op.f('ck_study_programs_status')),
    sa.ForeignKeyConstraint(['user_id', 'area_id'], ['study_areas.user_id', 'study_areas.id'], name=op.f('fk_study_programs_user_id_study_areas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_programs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_programs')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_study_programs_user_id_id'))
    )
    op.create_index(op.f('ix_study_programs_user_id'), 'study_programs', ['user_id'], unique=False)
    op.create_table('task_instances',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('pending','done','skipped')", name=op.f('ck_task_instances_status')),
    sa.ForeignKeyConstraint(['user_id', 'task_id'], ['tasks.user_id', 'tasks.id'], name=op.f('fk_task_instances_user_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_instances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_instances')),
    sa.UniqueConstraint('user_id', 'task_id', 'date', name=op.f('uq_task_instances_user_id_task_id_date'))
    )
    op.create_index(op.f('ix_task_instances_user_id'), 'task_instances', ['user_id'], unique=False)
    op.create_table('study_notebooks',
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('syllabus', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'area_id'], ['study_areas.user_id', 'study_areas.id'], name=op.f('fk_study_notebooks_user_id_study_areas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'program_id'], ['study_programs.user_id', 'study_programs.id'], name=op.f('fk_study_notebooks_user_id_study_programs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_notebooks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_notebooks')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_study_notebooks_user_id_id'))
    )
    op.create_index(op.f('ix_study_notebooks_user_id'), 'study_notebooks', ['user_id'], unique=False)
    op.create_table('study_targets',
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('board', sa.String(), nullable=True),
    sa.Column('edition', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('metadata_origin', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'program_id'], ['study_programs.user_id', 'study_programs.id'], name=op.f('fk_study_targets_user_id_study_programs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_targets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_targets')),
    sa.UniqueConstraint('user_id', 'program_id', name=op.f('uq_study_targets_user_id_program_id'))
    )
    op.create_index(op.f('ix_study_targets_user_id'), 'study_targets', ['user_id'], unique=False)
    op.create_table('flashcards',
    sa.Column('notebook_id', sa.Uuid(), nullable=False),
    sa.Column('deck_name', sa.String(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('next_review', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'notebook_id'], ['study_notebooks.user_id', 'study_notebooks.id'], name=op.f('fk_flashcards_user_id_study_notebooks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_flashcards_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flashcards')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_flashcards_user_id_id'))
    )
    op.create_index('ix_flashcards_owner_review', 'flashcards', ['user_id', 'next_review'], unique=False)
    op.create_index(op.f('ix_flashcards_user_id'), 'flashcards', ['user_id'], unique=False)
    op.create_table('rag_sources',
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('notebook_id', sa.Uuid(), nullable=True),
    sa.Column('generation', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(file_id, analysis_id, notebook_id) = 1', name=op.f('ck_rag_sources_one_source')),
    sa.ForeignKeyConstraint(['user_id', 'analysis_id'], ['edital_analyses.user_id', 'edital_analyses.id'], name=op.f('fk_rag_sources_user_id_edital_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'file_id'], ['files.user_id', 'files.id'], name=op.f('fk_rag_sources_user_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'notebook_id'], ['study_notebooks.user_id', 'study_notebooks.id'], name=op.f('fk_rag_sources_user_id_study_notebooks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rag_sources_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_sources')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_rag_sources_user_id_id'))
    )
    op.create_index(op.f('ix_rag_sources_user_id'), 'rag_sources', ['user_id'], unique=False)
    op.create_table('study_notes',
    sa.Column('notebook_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'notebook_id'], ['study_notebooks.user_id', 'study_notebooks.id'], name=op.f('fk_study_notes_user_id_study_notebooks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_notes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_notes'))
    )
    op.create_index(op.f('ix_study_notes_user_id'), 'study_notes', ['user_id'], unique=False)
    op.create_table('study_topics',
    sa.Column('notebook_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('topic_key', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'notebook_id'], ['study_notebooks.user_id', 'study_notebooks.id'], name=op.f('fk_study_topics_user_id_study_notebooks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'parent_id'], ['study_topics.user_id', 'study_topics.id'], name=op.f('fk_study_topics_user_id_study_topics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_topics_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_topics')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_study_topics_user_id_id')),
    sa.UniqueConstraint('user_id', 'notebook_id', 'topic_key', name=op.f('uq_study_topics_user_id_notebook_id_topic_key'))
    )
    op.create_index(op.f('ix_study_topics_user_id'), 'study_topics', ['user_id'], unique=False)
    op.create_table('flashcard_reviews',
    sa.Column('flashcard_id', sa.Uuid(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('quality BETWEEN 0 AND 5', name=op.f('ck_flashcard_reviews_quality')),
    sa.ForeignKeyConstraint(['user_id', 'flashcard_id'], ['flashcards.user_id', 'flashcards.id'], name=op.f('fk_flashcard_reviews_user_id_flashcards'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_flashcard_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flashcard_reviews'))
    )
    op.create_index(op.f('ix_flashcard_reviews_user_id'), 'flashcard_reviews', ['user_id'], unique=False)
    op.create_table('question_attempts',
    sa.Column('notebook_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('question_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_cause', sa.String(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name=op.f('ck_question_attempts_duration')),
    sa.CheckConstraint('total > 0 AND correct >= 0 AND correct <= total', name=op.f('ck_question_attempts_counts')),
    sa.ForeignKeyConstraint(['user_id', 'notebook_id'], ['study_notebooks.user_id', 'study_notebooks.id'], name=op.f('fk_question_attempts_user_id_study_notebooks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'topic_id'], ['study_topics.user_id', 'study_topics.id'], name=op.f('fk_question_attempts_user_id_study_topics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_question_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_attempts'))
    )
    op.create_index('ix_attempts_owner_answered', 'question_attempts', ['user_id', 'answered_at'], unique=False)
    op.create_index('ix_attempts_owner_topic', 'question_attempts', ['user_id', 'topic_id'], unique=False)
    op.create_index(op.f('ix_question_attempts_user_id'), 'question_attempts', ['user_id'], unique=False)
    op.create_table('rag_chunks',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('terms', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'source_id'], ['rag_sources.user_id', 'rag_sources.id'], name=op.f('fk_rag_chunks_user_id_rag_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rag_chunks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_chunks')),
    sa.UniqueConstraint('user_id', 'source_id', 'chunk_index', name=op.f('uq_rag_chunks_user_id_source_id_chunk_index'))
    )
    op.create_index(op.f('ix_rag_chunks_user_id'), 'rag_chunks', ['user_id'], unique=False)
    op.create_index('ix_rag_owner_hash', 'rag_chunks', ['user_id', 'content_hash'], unique=False)
    op.create_index('ix_rag_terms', 'rag_chunks', ['terms'], unique=False, postgresql_using='gin')
    op.create_table('study_review_events',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('next_review', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'topic_id'], ['study_topics.user_id', 'study_topics.id'], name=op.f('fk_study_review_events_user_id_study_topics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_review_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_review_events'))
    )
    op.create_index('ix_review_owner_topic_date', 'study_review_events', ['user_id', 'topic_id', 'reviewed_at'], unique=False)
    op.create_index(op.f('ix_study_review_events_user_id'), 'study_review_events', ['user_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('notebook_id', sa.Uuid(), nullable=True),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name=op.f('ck_study_sessions_interval')),
    sa.CheckConstraint('duration_minutes >= 0', name=op.f('ck_study_sessions_duration')),
    sa.ForeignKeyConstraint(['user_id', 'notebook_id'], ['study_notebooks.user_id', 'study_notebooks.id'], name=op.f('fk_study_sessions_user_id_study_notebooks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'topic_id'], ['study_topics.user_id', 'study_topics.id'], name=op.f('fk_study_sessions_user_id_study_topics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_sessions'))
    )
    op.create_index('ix_study_sessions_owner_date', 'study_sessions', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.create_table('topic_progress',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('studied', sa.Boolean(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('confident', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'topic_id'], ['study_topics.user_id', 'study_topics.id'], name=op.f('fk_topic_progress_user_id_study_topics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_topic_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_progress')),
    sa.UniqueConstraint('user_id', 'topic_id', name=op.f('uq_topic_progress_user_id_topic_id'))
    )
    op.create_index(op.f('ix_topic_progress_user_id'), 'topic_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_progress_user_id'), table_name='topic_progress')
    op.drop_table('topic_progress')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_index('ix_study_sessions_owner_date', table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_study_review_events_user_id'), table_name='study_review_events')
    op.drop_index('ix_review_owner_topic_date', table_name='study_review_events')
    op.drop_table('study_review_events')
    op.drop_index('ix_rag_terms', table_name='rag_chunks', postgresql_using='gin')
    op.drop_index('ix_rag_owner_hash', table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_user_id'), table_name='rag_chunks')
    op.drop_table('rag_chunks')
    op.drop_index(op.f('ix_question_attempts_user_id'), table_name='question_attempts')
    op.drop_index('ix_attempts_owner_topic', table_name='question_attempts')
    op.drop_index('ix_attempts_owner_answered', table_name='question_attempts')
    op.drop_table('question_attempts')
    op.drop_index(op.f('ix_flashcard_reviews_user_id'), table_name='flashcard_reviews')
    op.drop_table('flashcard_reviews')
    op.drop_index(op.f('ix_study_topics_user_id'), table_name='study_topics')
    op.drop_table('study_topics')
    op.drop_index(op.f('ix_study_notes_user_id'), table_name='study_notes')
    op.drop_table('study_notes')
    op.drop_index(op.f('ix_rag_sources_user_id'), table_name='rag_sources')
    op.drop_table('rag_sources')
    op.drop_index(op.f('ix_flashcards_user_id'), table_name='flashcards')
    op.drop_index('ix_flashcards_owner_review', table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_study_targets_user_id'), table_name='study_targets')
    op.drop_table('study_targets')
    op.drop_index(op.f('ix_study_notebooks_user_id'), table_name='study_notebooks')
    op.drop_table('study_notebooks')
    op.drop_index(op.f('ix_task_instances_user_id'), table_name='task_instances')
    op.drop_table('task_instances')
    op.drop_index(op.f('ix_study_programs_user_id'), table_name='study_programs')
    op.drop_table('study_programs')
    op.drop_index(op.f('ix_habit_checks_user_id'), table_name='habit_checks')
    op.drop_table('habit_checks')
    op.drop_index(op.f('ix_goal_checks_user_id'), table_name='goal_checks')
    op.drop_table('goal_checks')
    op.drop_index('ix_transactions_owner_date', table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_user_id'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    op.drop_index(op.f('ix_edital_analyses_user_id'), table_name='edital_analyses')
    op.drop_index('ix_analysis_owner_hash_version', table_name='edital_analyses')
    op.drop_table('edital_analyses')
    op.drop_index('ix_messages_conversation_created', table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_user_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_ai_action_audit_user_id'), table_name='ai_action_audit')
    op.drop_table('ai_action_audit')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index('ix_tasks_owner_date', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_study_areas_user_id'), table_name='study_areas')
    op.drop_table('study_areas')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_finance_categories_user_id'), table_name='finance_categories')
    op.drop_table('finance_categories')
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_credit_cards_user_id'), table_name='credit_cards')
    op.drop_table('credit_cards')
    op.drop_index('ix_calendar_owner_start', table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_ai_usage_user_id'), table_name='ai_usage')
    op.drop_index('ix_ai_usage_owner_created', table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_ai_preferences_user_id'), table_name='ai_preferences')
    op.drop_table('ai_preferences')
    op.drop_index(op.f('ix_ai_memories_user_id'), table_name='ai_memories')
    op.drop_table('ai_memories')
    op.drop_index('ix_events_status_lease', table_name='ai_events')
    op.drop_index('ix_events_owner_created', table_name='ai_events')
    op.drop_index(op.f('ix_ai_events_user_id'), table_name='ai_events')
    op.drop_table('ai_events')
    op.drop_index('uq_conversation_primary', table_name='ai_conversations', postgresql_where=sa.text('"primary" IS true'))
    op.drop_index('ix_conversations_owner_updated', table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_ai_actions_user_id'), table_name='ai_actions')
    op.drop_index('ix_actions_owner_status_expiry', table_name='ai_actions')
    op.drop_table('ai_actions')
    op.drop_table('activity_receipts')
    op.drop_index('uq_users_email_normalized', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
