"""enforce queue analysis ownership

Revision ID: 69c9b79ade0e
Revises: 5790e0d50771
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '69c9b79ade0e'
down_revision: Union[str, Sequence[str], None] = '5790e0d50771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_edital_jobs_user_id_edital_analyses'), 'edital_jobs', 'edital_analyses', ['user_id', 'analysis_id'], ['user_id', 'id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_edital_jobs_user_id_edital_analyses'), 'edital_jobs', type_='foreignkey')
    # ### end Alembic commands ###
