"""Typed notification schedules and delivery receipts

Revision ID: 7293cc85b93b
Revises: db4245d7971f
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7293cc85b93b'
down_revision: Union[str, Sequence[str], None] = 'db4245d7971f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_study_schedules_user_id_id'), 'study_schedules', ['user_id', 'id'])
    op.create_table('notifications',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('repeat', sa.String(), nullable=False),
    sa.Column('repeat_days', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('channels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('last_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_occurrence', sa.Date(), nullable=True),
    sa.Column('program_id', sa.Uuid(), nullable=True),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('reminder_kind', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("repeat IN ('none','daily','weekly','custom')", name=op.f('ck_notifications_repeat')),
    sa.ForeignKeyConstraint(['user_id', 'program_id'], ['study_programs.user_id', 'study_programs.id'], name=op.f('fk_notifications_user_id_study_programs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'schedule_id'], ['study_schedules.user_id', 'study_schedules.id'], name=op.f('fk_notifications_user_id_study_schedules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_notifications_user_id_id')),
    sa.UniqueConstraint('user_id', 'schedule_id', 'reminder_kind', name=op.f('uq_notifications_user_id_schedule_id_reminder_kind'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('occurrence', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'notification_id'], ['notifications.user_id', 'notifications.id'], name=op.f('fk_notification_deliveries_user_id_notifications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_deliveries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    sa.UniqueConstraint('user_id', 'notification_id', 'occurrence', 'channel', name=op.f('uq_notification_deliveries_user_id_notification_id_occurrence_channel'))
    )
    op.create_index(op.f('ix_notification_deliveries_user_id'), 'notification_deliveries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_deliveries_user_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_constraint(op.f('uq_study_schedules_user_id_id'), 'study_schedules', type_='unique')
    # ### end Alembic commands ###
