"""unique owned retrieval source references

Revision ID: 8721bc0c9cf9
Revises: 4e16ba167d61
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8721bc0c9cf9'
down_revision: Union[str, Sequence[str], None] = '4e16ba167d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_rag_sources_user_id_analysis_id'), 'rag_sources', ['user_id', 'analysis_id'])
    op.create_unique_constraint(op.f('uq_rag_sources_user_id_file_id'), 'rag_sources', ['user_id', 'file_id'])
    op.create_unique_constraint(op.f('uq_rag_sources_user_id_notebook_id'), 'rag_sources', ['user_id', 'notebook_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_rag_sources_user_id_notebook_id'), 'rag_sources', type_='unique')
    op.drop_constraint(op.f('uq_rag_sources_user_id_file_id'), 'rag_sources', type_='unique')
    op.drop_constraint(op.f('uq_rag_sources_user_id_analysis_id'), 'rag_sources', type_='unique')
    # ### end Alembic commands ###
