"""persist daily briefing cache

Revision ID: 93726080ad93
Revises: 060d04832219
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '93726080ad93'
down_revision: Union[str, Sequence[str], None] = '060d04832219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('greeting', sa.Text(), nullable=False),
    sa.Column('progress_summary', sa.Text(), nullable=False),
    sa.Column('pending_items', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('priority_action', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('tasks_pending', sa.Integer(), nullable=False),
    sa.Column('tasks_done', sa.Integer(), nullable=False),
    sa.Column('habits_pending', sa.Integer(), nullable=False),
    sa.Column('habits_done', sa.Integer(), nullable=False),
    sa.Column('study_minutes', sa.Integer(), nullable=False),
    sa.Column('meals_count', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('workouts_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name=op.f('ck_daily_summaries_score')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_summaries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_summaries')),
    sa.UniqueConstraint('user_id', 'date', name=op.f('uq_daily_summaries_user_id_date'))
    )
    op.create_index(op.f('ix_daily_summaries_user_id'), 'daily_summaries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_summaries_user_id'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    # ### end Alembic commands ###
