"""normalize exercises in manual workout logs

Revision ID: 99b09cc30936
Revises: c20af75ad6b0
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '99b09cc30936'
down_revision: Union[str, Sequence[str], None] = 'c20af75ad6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_unique_constraint(op.f('uq_workout_logs_user_id_id'), 'workout_logs', ['user_id', 'id'])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_log_exercises',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('sets_completed', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.String(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('muscle_group', sa.String(), nullable=False),
    sa.Column('tutorial', sa.Text(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.CheckConstraint('sets_completed BETWEEN 0 AND sets AND time_spent_seconds >= 0', name=op.f('ck_workout_log_exercises_completion')),
    sa.ForeignKeyConstraint(['user_id', 'log_id'], ['workout_logs.user_id', 'workout_logs.id'], name=op.f('fk_workout_log_exercises_user_id_workout_logs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_log_exercises_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_log_exercises')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_workout_log_exercises_user_id_id')),
    sa.UniqueConstraint('user_id', 'log_id', 'position', name=op.f('uq_workout_log_exercises_user_id_log_id_position'))
    )
    op.create_index(op.f('ix_workout_log_exercises_user_id'), 'workout_log_exercises', ['user_id'], unique=False)
    op.add_column('workout_sets', sa.Column('log_exercise_id', sa.Uuid(), nullable=True))
    op.alter_column('workout_sets', 'exercise_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(op.f('uq_workout_sets_user_id_log_exercise_id_position'), 'workout_sets', ['user_id', 'log_exercise_id', 'position'])
    op.create_foreign_key(op.f('fk_workout_sets_user_id_workout_log_exercises'), 'workout_sets', 'workout_log_exercises', ['user_id', 'log_exercise_id'], ['user_id', 'id'], ondelete='CASCADE')
    op.create_check_constraint(op.f('ck_workout_sets_one_exercise_source'),'workout_sets','(exercise_id IS NOT NULL)::integer + (log_exercise_id IS NOT NULL)::integer = 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('DELETE FROM workout_sets WHERE log_exercise_id IS NOT NULL')
    op.drop_constraint(op.f('ck_workout_sets_one_exercise_source'),'workout_sets',type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workout_sets_user_id_workout_log_exercises'), 'workout_sets', type_='foreignkey')
    op.drop_constraint(op.f('uq_workout_sets_user_id_log_exercise_id_position'), 'workout_sets', type_='unique')
    op.alter_column('workout_sets', 'exercise_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('workout_sets', 'log_exercise_id')
    op.drop_index(op.f('ix_workout_log_exercises_user_id'), table_name='workout_log_exercises')
    op.drop_table('workout_log_exercises')
    op.drop_constraint(op.f('uq_workout_logs_user_id_id'), 'workout_logs', type_='unique')
    # ### end Alembic commands ###
