"""persist typed report snapshots

Revision ID: 9b0a2c5d026b
Revises: 1d41972a807e
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9b0a2c5d026b'
down_revision: Union[str, Sequence[str], None] = '1d41972a807e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('insights', sa.Text(), nullable=False),
    sa.Column('definitions', sa.Text(), nullable=False),
    sa.Column('tasks', sa.Integer(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('habits', sa.Integer(), nullable=False),
    sa.Column('total_habits_completions', sa.Integer(), nullable=False),
    sa.Column('income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('expenses', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('goals_progress', sa.Float(), nullable=False),
    sa.Column('goal_checks', sa.Integer(), nullable=False),
    sa.Column('study_minutes', sa.Integer(), nullable=False),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('questions_correct', sa.Integer(), nullable=False),
    sa.Column('workouts', sa.Integer(), nullable=False),
    sa.Column('workout_minutes', sa.Integer(), nullable=False),
    sa.Column('meals', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('water_ml', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_reports_period')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index('ix_reports_owner_created', 'reports', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index('ix_reports_owner_created', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
