"""persist edital source metadata and pages

Revision ID: 9f463181b69a
Revises: e9760f903e6f
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9f463181b69a'
down_revision: Union[str, Sequence[str], None] = 'e9760f903e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edital_analyses', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('edital_analyses', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('edital_analyses', sa.Column('from_cache', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('edital_analyses', sa.Column('pages', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.alter_column('edital_analyses', 'from_cache', server_default=None)
    op.alter_column('edital_analyses', 'pages', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edital_analyses', 'pages')
    op.drop_column('edital_analyses', 'from_cache')
    op.drop_column('edital_analyses', 'expires_at')
    op.drop_column('edital_analyses', 'filename')
    # ### end Alembic commands ###
