"""study catalog archives and syllabus weighting

Revision ID: a0e1aba8b22c
Revises: d3fa62b2e3a2
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a0e1aba8b22c'
down_revision: Union[str, Sequence[str], None] = 'd3fa62b2e3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_areas', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('study_notebooks', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('study_notebooks', sa.Column('weight', sa.Float(), nullable=False, server_default='1'))
    op.add_column('study_notebooks', sa.Column('dificuldade', sa.String(), nullable=False, server_default='media'))
    op.add_column('study_notebooks', sa.Column('user_difficulty', sa.String(), nullable=True))
    op.add_column('study_notebooks', sa.Column('num_questoes_edital', sa.Integer(), nullable=True))
    op.add_column('study_notebooks', sa.Column('recursos_recomendados', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    for column in ('weight','dificuldade','recursos_recomendados'):
        op.alter_column('study_notebooks',column,server_default=None)
    op.add_column('study_topics', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('study_programs', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('study_topics', 'archived_at')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_programs', 'archived_at')
    op.drop_column('study_notebooks', 'recursos_recomendados')
    op.drop_column('study_notebooks', 'num_questoes_edital')
    op.drop_column('study_notebooks', 'user_difficulty')
    op.drop_column('study_notebooks', 'dificuldade')
    op.drop_column('study_notebooks', 'weight')
    op.drop_column('study_notebooks', 'archived_at')
    op.drop_column('study_areas', 'archived_at')
    # ### end Alembic commands ###
