"""owned daily motivational quotes

Revision ID: a600df30ea2f
Revises: 4125068ff630
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a600df30ea2f'
down_revision: Union[str, Sequence[str], None] = '4125068ff630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_quotes',
    sa.Column('motivational_date', sa.Date(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('workouts_this_week', sa.Integer(), nullable=False),
    sa.Column('habits_today', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_quotes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_quotes')),
    sa.UniqueConstraint('user_id', 'motivational_date', name=op.f('uq_daily_quotes_user_id_motivational_date'))
    )
    op.create_index(op.f('ix_daily_quotes_user_id'), 'daily_quotes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_quotes_user_id'), table_name='daily_quotes')
    op.drop_table('daily_quotes')
    # ### end Alembic commands ###
