"""persist edital program provenance and weekly schedules

Revision ID: aaf789704647
Revises: 69c9b79ade0e
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'aaf789704647'
down_revision: Union[str, Sequence[str], None] = '69c9b79ade0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_schedules',
    sa.Column('notebook_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('repeat', sa.Boolean(), nullable=False),
    sa.Column('tipo_estudo', sa.String(), nullable=False),
    sa.Column('prioridade', sa.String(), nullable=False),
    sa.Column('assuntos_foco', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("day_of_week IN ('monday','tuesday','wednesday','thursday','friday','saturday','sunday')", name=op.f('ck_study_schedules_day')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_study_schedules_interval')),
    sa.ForeignKeyConstraint(['user_id', 'notebook_id'], ['study_notebooks.user_id', 'study_notebooks.id'], name=op.f('fk_study_schedules_user_id_study_notebooks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_schedules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_schedules'))
    )
    op.create_index(op.f('ix_study_schedules_user_id'), 'study_schedules', ['user_id'], unique=False)
    op.add_column('study_notebooks', sa.Column('peso_fonte', sa.String(), nullable=False, server_default=''))
    op.alter_column('study_notebooks', 'peso_fonte', server_default=None)
    op.add_column('study_notebooks', sa.Column('peso_status', sa.String(), nullable=False, server_default='a_conferir'))
    op.alter_column('study_notebooks', 'peso_status', server_default=None)
    op.add_column('study_notebooks', sa.Column('num_questoes_fonte', sa.String(), nullable=False, server_default=''))
    op.alter_column('study_notebooks', 'num_questoes_fonte', server_default=None)
    op.add_column('study_notebooks', sa.Column('num_questoes_status', sa.String(), nullable=False, server_default='a_conferir'))
    op.alter_column('study_notebooks', 'num_questoes_status', server_default=None)
    op.add_column('study_notebooks', sa.Column('grupo', sa.String(), nullable=False, server_default=''))
    op.alter_column('study_notebooks', 'grupo', server_default=None)
    op.add_column('study_notebooks', sa.Column('fontes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.alter_column('study_notebooks', 'fontes', server_default=None)
    op.add_column('study_programs', sa.Column('source_type', sa.String(), nullable=False, server_default='manual'))
    op.alter_column('study_programs', 'source_type', server_default=None)
    op.add_column('study_programs', sa.Column('edital_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
    op.alter_column('study_programs', 'edital_data', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_programs', 'edital_data')
    op.drop_column('study_programs', 'source_type')
    op.drop_column('study_notebooks', 'fontes')
    op.drop_column('study_notebooks', 'grupo')
    op.drop_column('study_notebooks', 'num_questoes_status')
    op.drop_column('study_notebooks', 'num_questoes_fonte')
    op.drop_column('study_notebooks', 'peso_status')
    op.drop_column('study_notebooks', 'peso_fonte')
    op.drop_index(op.f('ix_study_schedules_user_id'), table_name='study_schedules')
    op.drop_table('study_schedules')
    # ### end Alembic commands ###
