"""dated study entries drafts and unlinked question facts

Revision ID: b64cd6f47873
Revises: 3b22081c7fa1
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b64cd6f47873'
down_revision: Union[str, Sequence[str], None] = '3b22081c7fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plans',
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('availability', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('block_minutes', sa.Integer(), nullable=False),
    sa.Column('adaptive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('array_length(availability,1) = 7', name=op.f('ck_study_plans_availability')),
    sa.CheckConstraint('end_date >= start_date AND block_minutes BETWEEN 15 AND 120', name=op.f('ck_study_plans_settings')),
    sa.ForeignKeyConstraint(['user_id', 'program_id'], ['study_programs.user_id', 'study_programs.id'], name=op.f('fk_study_plans_user_id_study_programs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plans')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_study_plans_user_id_id')),
    sa.UniqueConstraint('user_id', 'program_id', name=op.f('uq_study_plans_user_id_program_id'))
    )
    op.create_index(op.f('ix_study_plans_user_id'), 'study_plans', ['user_id'], unique=False)
    op.create_table('study_drafts',
    sa.Column('notebook_id', sa.Uuid(), nullable=False),
    sa.Column('topic_key', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('revision > 0', name=op.f('ck_study_drafts_revision')),
    sa.ForeignKeyConstraint(['user_id', 'notebook_id'], ['study_notebooks.user_id', 'study_notebooks.id'], name=op.f('fk_study_drafts_user_id_study_notebooks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_drafts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_drafts')),
    sa.UniqueConstraint('user_id', 'notebook_id', 'topic_key', name=op.f('uq_study_drafts_user_id_notebook_id_topic_key'))
    )
    op.create_index(op.f('ix_study_drafts_user_id'), 'study_drafts', ['user_id'], unique=False)
    op.create_table('study_plan_entries',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('notebook_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.Column('fixed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('minutes > 0', name=op.f('ck_study_plan_entries_minutes')),
    sa.ForeignKeyConstraint(['user_id', 'notebook_id'], ['study_notebooks.user_id', 'study_notebooks.id'], name=op.f('fk_study_plan_entries_user_id_study_notebooks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'plan_id'], ['study_plans.user_id', 'study_plans.id'], name=op.f('fk_study_plan_entries_user_id_study_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_plan_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plan_entries'))
    )
    op.create_index('ix_plan_entries_owner_date', 'study_plan_entries', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_study_plan_entries_user_id'), 'study_plan_entries', ['user_id'], unique=False)
    op.alter_column('question_attempts', 'notebook_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_attempts', 'notebook_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_study_plan_entries_user_id'), table_name='study_plan_entries')
    op.drop_index('ix_plan_entries_owner_date', table_name='study_plan_entries')
    op.drop_table('study_plan_entries')
    op.drop_index(op.f('ix_study_drafts_user_id'), table_name='study_drafts')
    op.drop_table('study_drafts')
    op.drop_index(op.f('ix_study_plans_user_id'), table_name='study_plans')
    op.drop_table('study_plans')
    # ### end Alembic commands ###
