"""normalize workout sessions sets and nutrition

Revision ID: b74fa82e3a67
Revises: c43f2a70b921
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b74fa82e3a67'
down_revision: Union[str, Sequence[str], None] = 'c43f2a70b921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_meals_user_id_id'))
    )
    op.create_index('ix_meals_owner_date', 'meals', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('nutrition_goals',
    sa.Column('daily_calories', sa.Integer(), nullable=False),
    sa.Column('daily_protein', sa.Float(), nullable=False),
    sa.Column('daily_carbs', sa.Float(), nullable=False),
    sa.Column('daily_fat', sa.Float(), nullable=False),
    sa.Column('water_goal_ml', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('daily_calories > 0 AND water_goal_ml > 0', name=op.f('ck_nutrition_goals_targets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_nutrition_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_goals')),
    sa.UniqueConstraint('user_id', name=op.f('uq_nutrition_goals_user_id'))
    )
    op.create_index(op.f('ix_nutrition_goals_user_id'), 'nutrition_goals', ['user_id'], unique=False)
    op.create_table('water_logs',
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_ml > 0', name=op.f('ck_water_logs_amount')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_water_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_water_logs'))
    )
    op.create_index(op.f('ix_water_logs_user_id'), 'water_logs', ['user_id'], unique=False)
    op.create_index('ix_water_owner_date', 'water_logs', ['user_id', 'date'], unique=False)
    op.create_table('workout_plans',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_duration', sa.String(), nullable=False),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('generated_by_ai', sa.Boolean(), nullable=False),
    sa.Column('generation_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_plans')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_workout_plans_user_id_id'))
    )
    op.create_index(op.f('ix_workout_plans_user_id'), 'workout_plans', ['user_id'], unique=False)
    op.create_table('meal_items',
    sa.Column('meal_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('quantity >= 0 AND calories >= 0', name=op.f('ck_meal_items_quantities')),
    sa.ForeignKeyConstraint(['user_id', 'meal_id'], ['meals.user_id', 'meals.id'], name=op.f('fk_meal_items_user_id_meals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meal_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_items')),
    sa.UniqueConstraint('user_id', 'meal_id', 'position', name=op.f('uq_meal_items_user_id_meal_id_position'))
    )
    op.create_index(op.f('ix_meal_items_user_id'), 'meal_items', ['user_id'], unique=False)
    op.create_table('workout_plan_days',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('week >= 1 AND position >= 0', name=op.f('ck_workout_plan_days_position')),
    sa.ForeignKeyConstraint(['user_id', 'plan_id'], ['workout_plans.user_id', 'workout_plans.id'], name=op.f('fk_workout_plan_days_user_id_workout_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_plan_days_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_plan_days')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_workout_plan_days_user_id_id')),
    sa.UniqueConstraint('user_id', 'plan_id', 'position', name=op.f('uq_workout_plan_days_user_id_plan_id_position'))
    )
    op.create_index(op.f('ix_workout_plan_days_user_id'), 'workout_plan_days', ['user_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('current_exercise_idx', sa.Integer(), nullable=False),
    sa.Column('rest_timer_seconds', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('active','completed','abandoned')", name=op.f('ck_workout_sessions_status')),
    sa.CheckConstraint('total_duration_seconds >= 0', name=op.f('ck_workout_sessions_duration')),
    sa.ForeignKeyConstraint(['user_id', 'plan_id'], ['workout_plans.user_id', 'workout_plans.id'], name=op.f('fk_workout_sessions_user_id_workout_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_sessions')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_workout_sessions_user_id_id'))
    )
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_index('uq_workout_active_user', 'workout_sessions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('plan_exercises',
    sa.Column('day_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.String(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('muscle_group', sa.String(), nullable=False),
    sa.Column('tutorial', sa.Text(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.CheckConstraint('sets > 0 AND rest_seconds >= 0', name=op.f('ck_plan_exercises_sets_rest')),
    sa.ForeignKeyConstraint(['user_id', 'day_id'], ['workout_plan_days.user_id', 'workout_plan_days.id'], name=op.f('fk_plan_exercises_user_id_workout_plan_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_plan_exercises_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_exercises')),
    sa.UniqueConstraint('user_id', 'day_id', 'position', name=op.f('uq_plan_exercises_user_id_day_id_position'))
    )
    op.create_index(op.f('ix_plan_exercises_user_id'), 'plan_exercises', ['user_id'], unique=False)
    op.create_table('session_exercises',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('sets_completed', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.String(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('muscle_group', sa.String(), nullable=False),
    sa.Column('tutorial', sa.Text(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.CheckConstraint('sets_completed BETWEEN 0 AND sets AND time_spent_seconds >= 0', name=op.f('ck_session_exercises_completion')),
    sa.ForeignKeyConstraint(['user_id', 'session_id'], ['workout_sessions.user_id', 'workout_sessions.id'], name=op.f('fk_session_exercises_user_id_workout_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_session_exercises_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_exercises')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_session_exercises_user_id_id')),
    sa.UniqueConstraint('user_id', 'session_id', 'position', name=op.f('uq_session_exercises_user_id_session_id_position'))
    )
    op.create_index(op.f('ix_session_exercises_user_id'), 'session_exercises', ['user_id'], unique=False)
    op.create_table('workout_logs',
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes >= 0', name=op.f('ck_workout_logs_duration')),
    sa.ForeignKeyConstraint(['user_id', 'plan_id'], ['workout_plans.user_id', 'workout_plans.id'], name=op.f('fk_workout_logs_user_id_workout_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'session_id'], ['workout_sessions.user_id', 'workout_sessions.id'], name=op.f('fk_workout_logs_user_id_workout_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_logs')),
    sa.UniqueConstraint('user_id', 'session_id', name=op.f('uq_workout_logs_user_id_session_id'))
    )
    op.create_index('ix_workout_logs_owner_date', 'workout_logs', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_workout_logs_user_id'), 'workout_logs', ['user_id'], unique=False)
    op.create_table('workout_sets',
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('reps IS NULL OR reps >= 0', name=op.f('ck_workout_sets_reps')),
    sa.CheckConstraint('rpe IS NULL OR rpe BETWEEN 0 AND 10', name=op.f('ck_workout_sets_rpe')),
    sa.ForeignKeyConstraint(['user_id', 'exercise_id'], ['session_exercises.user_id', 'session_exercises.id'], name=op.f('fk_workout_sets_user_id_session_exercises'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_sets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_sets')),
    sa.UniqueConstraint('user_id', 'exercise_id', 'position', name=op.f('uq_workout_sets_user_id_exercise_id_position'))
    )
    op.create_index(op.f('ix_workout_sets_user_id'), 'workout_sets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sets_user_id'), table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_index(op.f('ix_workout_logs_user_id'), table_name='workout_logs')
    op.drop_index('ix_workout_logs_owner_date', table_name='workout_logs')
    op.drop_table('workout_logs')
    op.drop_index(op.f('ix_session_exercises_user_id'), table_name='session_exercises')
    op.drop_table('session_exercises')
    op.drop_index(op.f('ix_plan_exercises_user_id'), table_name='plan_exercises')
    op.drop_table('plan_exercises')
    op.drop_index('uq_workout_active_user', table_name='workout_sessions', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_workout_plan_days_user_id'), table_name='workout_plan_days')
    op.drop_table('workout_plan_days')
    op.drop_index(op.f('ix_meal_items_user_id'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_workout_plans_user_id'), table_name='workout_plans')
    op.drop_table('workout_plans')
    op.drop_index('ix_water_owner_date', table_name='water_logs')
    op.drop_index(op.f('ix_water_logs_user_id'), table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index(op.f('ix_nutrition_goals_user_id'), table_name='nutrition_goals')
    op.drop_table('nutrition_goals')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index('ix_meals_owner_date', table_name='meals')
    op.drop_table('meals')
    # ### end Alembic commands ###
