"""preserve workout plan metadata and archive

Revision ID: b91a1161f708
Revises: cb8efdf00b9f
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b91a1161f708'
down_revision: Union[str, Sequence[str], None] = 'cb8efdf00b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_plan_days', sa.Column('split_label', sa.String(), nullable=False, server_default=""))
    op.add_column('workout_plan_days', sa.Column('progression_focus', sa.String(), nullable=False, server_default=""))
    op.add_column('workout_plan_days', sa.Column('progression_notes', sa.Text(), nullable=False, server_default=""))
    op.add_column('workout_plans', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    for column in ('split_label','progression_focus','progression_notes'):
        op.alter_column('workout_plan_days',column,server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_plans', 'archived_at')
    op.drop_column('workout_plan_days', 'progression_notes')
    op.drop_column('workout_plan_days', 'progression_focus')
    op.drop_column('workout_plan_days', 'split_label')
    # ### end Alembic commands ###
