"""link improved workout plans to their source

Revision ID: c20af75ad6b0
Revises: b91a1161f708
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c20af75ad6b0'
down_revision: Union[str, Sequence[str], None] = 'b91a1161f708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_plans', sa.Column('improved_from', sa.Uuid(), nullable=True))
    op.add_column('workout_plans', sa.Column('improvements_summary', sa.Text(), nullable=True))
    op.create_foreign_key(op.f('fk_workout_plans_user_id_workout_plans'), 'workout_plans', 'workout_plans', ['user_id', 'improved_from'], ['user_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workout_plans_user_id_workout_plans'), 'workout_plans', type_='foreignkey')
    op.drop_column('workout_plans', 'improvements_summary')
    op.drop_column('workout_plans', 'improved_from')
    # ### end Alembic commands ###
