"""preserve generated study material provenance

Revision ID: cb8efdf00b9f
Revises: d04654f48d58
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cb8efdf00b9f'
down_revision: Union[str, Sequence[str], None] = 'd04654f48d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('ai_generated', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('flashcards', sa.Column('source_pdf', sa.String(), nullable=True))
    op.add_column('study_notes', sa.Column('ai_generated', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('study_notes', sa.Column('source_pdf', sa.String(), nullable=True))
    op.alter_column('flashcards','ai_generated',server_default=None)
    op.alter_column('study_notes','ai_generated',server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_notes', 'source_pdf')
    op.drop_column('study_notes', 'ai_generated')
    op.drop_column('flashcards', 'source_pdf')
    op.drop_column('flashcards', 'ai_generated')
    # ### end Alembic commands ###
