"""persist mindmaps and essay corrections

Revision ID: d04654f48d58
Revises: 13ef5c5fbe1f
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd04654f48d58'
down_revision: Union[str, Sequence[str], None] = '13ef5c5fbe1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_essay_corrections',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('correction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_essay_corrections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_essay_corrections'))
    )
    op.create_index('ix_essays_owner_created', 'study_essay_corrections', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_study_essay_corrections_user_id'), 'study_essay_corrections', ['user_id'], unique=False)
    op.create_table('study_mindmaps',
    sa.Column('notebook_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('file','text','topic','notebook')", name=op.f('ck_study_mindmaps_source')),
    sa.ForeignKeyConstraint(['user_id', 'notebook_id'], ['study_notebooks.user_id', 'study_notebooks.id'], name=op.f('fk_study_mindmaps_user_id_study_notebooks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_mindmaps_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_mindmaps'))
    )
    op.create_index('ix_mindmaps_owner_created', 'study_mindmaps', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_study_mindmaps_user_id'), 'study_mindmaps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_mindmaps_user_id'), table_name='study_mindmaps')
    op.drop_index('ix_mindmaps_owner_created', table_name='study_mindmaps')
    op.drop_table('study_mindmaps')
    op.drop_index(op.f('ix_study_essay_corrections_user_id'), table_name='study_essay_corrections')
    op.drop_index('ix_essays_owner_created', table_name='study_essay_corrections')
    op.drop_table('study_essay_corrections')
    # ### end Alembic commands ###
