"""archive goals without deleting completion evidence

Revision ID: d3fa62b2e3a2
Revises: 0e61828b3519
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd3fa62b2e3a2'
down_revision: Union[str, Sequence[str], None] = '0e61828b3519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'archived_at')
    # ### end Alembic commands ###
