"""typed contest sources updates and host throttles

Revision ID: db4245d7971f
Revises: a600df30ea2f
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'db4245d7971f'
down_revision: Union[str, Sequence[str], None] = 'a600df30ea2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_host_limits',
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('next_poll', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('host', name=op.f('pk_contest_host_limits'))
    )
    op.create_table('contest_sources',
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('trust', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('terms_confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_poll', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_token', sa.Uuid(), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('modified', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'program_id'], ['study_programs.user_id', 'study_programs.id'], name=op.f('fk_contest_sources_user_id_study_programs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_contest_sources_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contest_sources')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_contest_sources_user_id_id')),
    sa.UniqueConstraint('user_id', 'program_id', 'url_hash', name=op.f('uq_contest_sources_user_id_program_id_url_hash'))
    )
    op.create_index('ix_contest_sources_enabled_next', 'contest_sources', ['enabled', 'next_poll'], unique=False)
    op.create_index(op.f('ix_contest_sources_user_id'), 'contest_sources', ['user_id'], unique=False)
    op.create_table('contest_updates',
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('hash_basis', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('official', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('text_extraction', sa.String(), nullable=True),
    sa.Column('text_partial', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'program_id'], ['study_programs.user_id', 'study_programs.id'], name=op.f('fk_contest_updates_user_id_study_programs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'source_id'], ['contest_sources.user_id', 'contest_sources.id'], name=op.f('fk_contest_updates_user_id_contest_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_contest_updates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contest_updates')),
    sa.UniqueConstraint('user_id', 'source_id', 'content_hash', name=op.f('uq_contest_updates_user_id_source_id_content_hash'))
    )
    op.create_index('ix_contest_updates_owner_program_detected', 'contest_updates', ['user_id', 'program_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_contest_updates_user_id'), 'contest_updates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contest_updates_user_id'), table_name='contest_updates')
    op.drop_index('ix_contest_updates_owner_program_detected', table_name='contest_updates')
    op.drop_table('contest_updates')
    op.drop_index(op.f('ix_contest_sources_user_id'), table_name='contest_sources')
    op.drop_index('ix_contest_sources_enabled_next', table_name='contest_sources')
    op.drop_table('contest_sources')
    op.drop_table('contest_host_limits')
    # ### end Alembic commands ###
