"""persist recipes and ingredients

Revision ID: e8f211413453
Revises: 32afa15613bd
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e8f211413453'
down_revision: Union[str, Sequence[str], None] = '32afa15613bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=False),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('calories_per_serving', sa.Float(), nullable=False),
    sa.Column('protein_per_serving', sa.Float(), nullable=False),
    sa.Column('carbs_per_serving', sa.Float(), nullable=False),
    sa.Column('fat_per_serving', sa.Float(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('tips', sa.Text(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('calories_per_serving >= 0 AND protein_per_serving >= 0 AND carbs_per_serving >= 0 AND fat_per_serving >= 0', name=op.f('ck_recipes_macros')),
    sa.CheckConstraint('servings > 0 AND prep_time_minutes >= 0 AND cook_time_minutes >= 0', name=op.f('ck_recipes_portions_time')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recipes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes')),
    sa.UniqueConstraint('user_id', 'id', name=op.f('uq_recipes_user_id_id'))
    )
    op.create_index('ix_recipes_owner_created', 'recipes', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'recipe_id'], ['recipes.user_id', 'recipes.id'], name=op.f('fk_recipe_ingredients_user_id_recipes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recipe_ingredients_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredients')),
    sa.UniqueConstraint('user_id', 'recipe_id', 'position', name=op.f('uq_recipe_ingredients_user_id_recipe_id_position'))
    )
    op.create_index(op.f('ix_recipe_ingredients_user_id'), 'recipe_ingredients', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_ingredients_user_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.drop_index('ix_recipes_owner_created', table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
