"""preserve target name and exam date

Revision ID: e9760f903e6f
Revises: 3968deb85ca6
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e9760f903e6f'
down_revision: Union[str, Sequence[str], None] = '3968deb85ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_targets', sa.Column('name', sa.String(), nullable=True))
    op.add_column('study_targets', sa.Column('exam_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_targets', 'exam_date')
    op.drop_column('study_targets', 'name')
    # ### end Alembic commands ###
