"""preserve flashcard tags and review history

Revision ID: ffe3963e1090
Revises: 446593f7d365
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ffe3963e1090'
down_revision: Union[str, Sequence[str], None] = '446593f7d365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('flashcards', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False, server_default=sa.text("'{}'::varchar[]")))
    op.alter_column('flashcards','tags',server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcards', 'tags')
    op.drop_column('flashcards', 'archived_at')
    # ### end Alembic commands ###
